/* accept-segctl.js — the segmented control (view.js segLens / attachSegmented; 界面): the static rows (34 屏幕时间 geometry) and the interaction
   sections that were accept.js's "segctl" sections — §1 G-rules, the lift / glass / warp rows, the tap chain, the value-change content transition
   (B3 / R20c), the R7 platter fade, #9② quick taps, the re-render rows; plus the segment-tap-highlight / tab-bar-not-rebuilt row. Split out of
   accept.js 2026-09-20 (BOARD 收尾单 ②); row texts and expected values unchanged. R.n = the page's render() count (accept.js's wrapper). */
(function () {
  if (!window.ACCEPT) return;
  ACCEPT.add(async function acceptSegctl(ctx) {
    const { check, num, col, sleep, settle, raf, sec, segRest, tabRest, fadeRest, at, pev, cs, px, T, dark, near, rgb, same, fmt, satTop, varColor, probe, q, bs, onText, thisShift, R } = ctx;
    sec("static", { layer: "static" });
  /* Segmented control (状态 tab, 早班/晚班; 34 屏幕时间) */
  const segc = document.querySelector(".segctl");
  if (segc) {
    const r = segc.getBoundingClientRect();
    num("分段控件高 32（--ios-segment-h）", 32, r.height); num("分段控件圆角 16（--ios-segment-radius）", 16, px(cs(segc).borderTopLeftRadius));
    col("分段轨道 tertiarySystemFill（--ios-segment-track）", dark ? [118, 118, 128, .24] : [118, 118, 128, .12], cs(segc).backgroundColor);
    num("分段控件宽 = 卡片宽", innerWidth - 40, r.width);
    const lens = segc.querySelector(".lens"), b = segc.querySelector("button");
    if (lens) { num("分段透镜高 28（--ios-segment-lens-h）", 28, lens.getBoundingClientRect().height); num("分段透镜圆角 14（--ios-segment-lens-radius）", 14, px(cs(lens).borderTopLeftRadius)); num("分段透镜内缩 2（--ios-segment-lens-pad）", 2, lens.getBoundingClientRect().top - r.top);
      col("分段选中段 = _controlForegroundColor（--ios-segment-selected-bg）", dark ? [235, 235, 245, .3] : [255, 255, 255], cs(lens).backgroundColor);
      check("分段选中段无阴影（--ios-segment-selected-shadow）", "none", cs(lens).boxShadow, cs(lens).boxShadow === "none");
      check("分段静止平台普通合成（menu-card-material.md §2 更正：kCAFilterPlusL 只在 useSpringBoardVibrancy 位置位的分支 0x1c4135084–0x1c413508c；探针 sdfdump ④ compositingFilter 无）→ source-over，不加 blend / isolation", "normal · auto", `${cs(lens).mixBlendMode} · ${cs(segc).isolation}`, cs(lens).mixBlendMode === "normal" && cs(segc).isolation === "auto");
      check("分段选中段无滤镜（--ios-segment-selected-filter）", "none", (cs(lens).backdropFilter || cs(lens).webkitBackdropFilter || "none"), /^none$/.test(cs(lens).backdropFilter || cs(lens).webkitBackdropFilter || "none")); }
    if (b) { num("分段文字 13（--ios-segment-label-size）", 13, px(cs(b).fontSize), 0.05); check("分段选中字重 500（--ios-medium-weight）", 500, cs(segc.querySelector("button.on") || b).fontWeight, String(cs(segc.querySelector("button.on") || b).fontWeight) === "500"); }
  }
  if (sec("gestures", { layer: "timing" }) && q()) {
    const start = onText();
    /* §1 G15: touch-down on the unselected segment - value, lens and content unchanged; its label dims towards .2 over .43 s */
    let seg = q(), other = bs().find((b) => !b.classList.contains("on")), want = other.textContent, i0 = seg.style.getPropertyValue("--i");
    const r0 = R.n; pev(seg, "pointerdown", at(other));
    check("分段 G15 按下未选中段：index / 透镜 / 内容都不动", start, `${onText()} --i=${seg.style.getPropertyValue("--i")} renders+${R.n - r0}`, onText() === start && seg.style.getPropertyValue("--i") === i0 && R.n === r0 && thisShift(start));
    check("分段 G15 按下未选中段：标签变暗 .2 / .43 s ease-out（--ios-touch-segment-dim-*）", "opacity→.2 .43s", `${cs(other).opacity}→${other.classList.contains("dim") ? ".2" : "?"} ${cs(other).transitionDuration}`, other.classList.contains("dim") && /0\.43s/.test(cs(other).transitionDuration));
    /* §1 G3: a 300 ms hold still selects nothing */
    await sleep(300);
    check("分段 G3 按住 300 ms 不选中", start, onText(), onText() === start && R.n === r0);
    /* §1 G1–G3 + B3: the up commits index + change + content together, in the up's own task (view.js SEG_VC_NOW, 换值即抬手 — 监督局 09-19 15:5x; the native's
       switch shows at up +50…92 in its recordings, seg-value-change-content.md §0, the page's with the +66 ms timer at +136…143 on the phone, data 78284dd) */
    const t0 = performance.now(); pev(seg, "pointerup", at(other)); const dt = performance.now() - t0;
    check("分段 G1 抬手 +0：换值即抬手——选中态（标签 .on）与内容同一任务一帧替换（view.js SEG_VC_NOW；原 +66 计时器 + vcsplit 在真机落到抬手 +136…143，原生 +50…92 ← seg-value-change-content.md §0 / 数据 78284dd；?vcnow=0 回计时器）", `${want} renders+1`, `${onText()} renders+${R.n - r0}`, onText() === want && R.n === r0 + 1);
    await sleep(100);
    check("分段 G1 抬手 +100 ms：选中态与内容保持已换（只重画一次）；透镜由点按链自抬手起动", want, `${onText()} renders+${R.n - r0}`, onText() === want && thisShift(want) && R.n === r0 + 1);
    /* R20c (seg-value-change-content.md §5a / §5b): the two labels that changed cross-dissolve over 0.2 s on cubic-bezier(.25,.1,.25,1) — at +100 ms two ghosts per
       changed button (old fading out, new fading in), the real text transparent; the ghosts' transition is that curve and duration; by +260 ms the ghosts are
       gone and the real text shows the new weight */
    { const ghosts = [...q().querySelectorAll(".segx")], onB = bs().find((b) => b.classList.contains("on")), cg = ghosts[0] ? getComputedStyle(ghosts[0]) : null;
      const ops = ghosts.map((g) => parseFloat(getComputedStyle(g).opacity));
      check("R20c 换值 +100 ms：换了的两段各两张标签位图叠淡（.segx 4 张，旧淡出 / 新淡入途中 0 < α < 1）、过渡 .2 s cubic-bezier(.25,.1,.25,1)、真字暂透明", "4 ghosts mid-fade · .2s bezier · transparent", `${ghosts.length} ghosts α ${ops.map((o) => o.toFixed(2)).join("/")} · ${cg ? cg.transitionDuration + " " + cg.transitionTimingFunction : "-"} · color ${onB ? getComputedStyle(onB).color : "-"}`, ghosts.length === 4 && ops.every((o) => o > 0.02 && o < 0.98) && !!cg && parseFloat(cg.transitionDuration) === 0.2 && /0\.25, 0\.1, 0\.25, 1/.test(cg.transitionTimingFunction) && !!onB && getComputedStyle(onB).color === "rgba(0, 0, 0, 0)");
      /* the +260 ms state is captured by a timer (the rows below keep their own timing) and judged after the +476 row */
      window.__r20cLater = new Promise((res) => setTimeout(async () => { const onB2 = bs().find((b) => b.classList.contains("on")); let late = 0;
        const anims = onB2 && onB2.getAnimations ? onB2.getAnimations() : [];   // S1 / A16 (red once under load: weight 499.75 at the wall-clock +260): a still-running weight / colour transition of the label is waited to its own end
        if (anims.length) { const t0 = performance.now(); try { await Promise.all(anims.map((a) => a.finished)); } catch (e) {} late = Math.round(performance.now() - t0); }
        res({ left: q().querySelectorAll(".segx").length, color: onB2 ? getComputedStyle(onB2).color : "-", weight: onB2 ? getComputedStyle(onB2).fontWeight : "-", late }); }, 160)); }
    { const gone = document.querySelectorAll(".flipgone"), moved = [...document.querySelectorAll("#app > section")].filter((s) => /translateY\((-?[\d.]+)px\)/.test(s.style.transform) && Math.abs(parseFloat(s.style.transform.match(/translateY\((-?[\d.]+)px\)/)[1])) > 20);
      const elF = performance.now() - t0, wantF = tabAt(FLIP_DEL_FADE, elF);   // the switch is at the up itself now: the clone's opacity read against view.js's §1 table at the actual elapsed time
      check("分段 B3 换值后 +100 ms：卡片内容已换（renders+1）；删的行原地克隆在淡出途中（起 .72，+193 到 .04，切换即抬手：按实际时刻查 FLIP_DEL_FADE ± .15，一帧 rAF 步进的滞后）、下方内容仍从原位（+行高）上滑（seg-value-change-content.md §0/§1，采样）", `clone ${wantF.toFixed(2)} ± .15 @ ${elF.toFixed(0)} ms · sections offset`, `${gone.length} clones ${gone.length ? cs(gone[0]).opacity : "-"} · ${moved.length} sections offset ${moved.length ? moved[0].style.transform : "-"}`, gone.length > 0 && Math.abs(parseFloat(cs(gone[0]).opacity) - wantF) <= .15 && moved.length > 0); }
    const lensNow = q().querySelector(".lens");
    { const lp0 = q().__lensLoop; check("分段 G1 抬手：点按走 segLens 点按链（seg-lens-refraction §4.4：up +82 抬起几何 ζ1/.25 原位、+92 材质、+98 换值行程 ζ.85/.4、+443/+450 落回；view.js SEG_TAP_T），不再走 CSS 关键帧滑行", "loop phase tap · no lens-stretch", `${lp0 ? (lp0.state.done ? "done" : (lp0.diag ? lp0.diag.phase : "no tick")) : "no loop"} · ${cs(lensNow).animationName}`, !!lp0 && !lp0.state.done && !!lp0.diag && lp0.diag.phase === "tap" && cs(lensNow).animationName !== "lens-stretch"); }
    await sleep(192);
    /* A16 (red three times on light first runs): the sample is the DRIVER's last tick — its own time since the up, the width and centre it wrote —
       not a wall-clock elapsed against a DOM rect read up to a frame later (and, per the R0② investigation, while an overflowing lens canvas may be
       widening the layout viewport under the control) */
    { const L = window.__segLens, lp = parseFloat(q().style.getPropertyValue("--lp") || "0"), el = L && L.since_up != null ? L.since_up : (performance.now() - t0) / 1000, c = L ? L.x_screen : NaN, lw = L ? L.w_screen : NaN, lr = { width: lw };
      const NT = [[.236, 229.65, 230.3], [.253, 240.8, 235.8], [.271, 249.8, 240.8], [.286, 257.15, 242.9], [.303, 263.6, 241.6], [.320, 269.25, 238.3], [.336, 274.6, 233.8], [.353, 279.55, 228.5], [.370, 284.2, 222.8]];   // native seg-native-tap-frames.json: t since up → lens centre (control coords = page − 20), width
      let nc = NT[NT.length - 1][1], nw = NT[NT.length - 1][2]; for (let i = 1; i < NT.length; i++) if (el <= NT[i][0]) { const a = NT[i - 1], b = NT[i], u = Math.max(0, (el - a[0]) / (b[0] - a[0])); nc = a[1] + (b[1] - a[1]) * u; nw = a[2] + (b[2] - a[2]) * u; break; }
      /* the centre carries the flex drift (B5: ≈ −11 pt while accelerating); a frame gap > 50 ms resets the integrator (flex-interaction.md §1 hysteresis .05, the read
         mechanism) and the drift goes to 0 — so on a stalled run the centre is reported, not judged (A16: the gap is the environment, the reset the native rule) */
      const gap = L && L.max_dt_up != null ? L.max_dt_up : 0, stalled = gap > .034;
      check(`分段 G1 抬手 +272 ms：玻璃滑行中（--lp ≥ .8）、拉长（原生 seg-native-tap-frames.json 同时刻插值：中心 / 宽，控件坐标；容 ± 12；按驱动器本帧：__segLens.since_up / w_screen / x_screen，A15；抬手后最大帧隔 > 34 ms 时中心只记不判——积分器 .05 s 滞后复位使漂移归零）`, `lp ≥ .8 · w ${nw.toFixed(1)} ± 12 · centre ${nc.toFixed(1)} ± 12 @ ${el.toFixed(3)}`, `lp ${lp.toFixed(3)} · w ${isNaN(lw) ? "-" : lw.toFixed(1)} · centre ${isNaN(c) ? "-" : c.toFixed(1)} @ tick ${L ? L.tick : "-"} · max frame gap ${(gap * 1000).toFixed(0)} ms${stalled ? "（停顿，中心不判）" : ""}`, !!L && lp >= .8 && Math.abs(lw - nw) <= 12 && (stalled || Math.abs(c - nc) <= 12)); }
    { const gone = document.querySelectorAll(".flipgone"), moved = [...document.querySelectorAll("#app > section")].filter((s) => /translateY/.test(s.style.transform)), insR = [...document.querySelectorAll("#app .row")].filter((r) => r.style.opacity !== "" && parseFloat(r.style.opacity) < 1);
      const elI = performance.now() - t0, wantI = tabAt(FLIP_INS, elI);   // the inserted rows against view.js's §2 table at the actual elapsed time (the switch is at the up)
      check("分段 B3 抬手 +292 ms：删的行淡到 ≤ .10（§1 +193 .04）、下方内容上滑途中（§0 +177 剩 24/133，+400 到位）、插的行淡入途中（§2 表按实际时刻查 FLIP_INS ± .15）", `clone ≤ .12 · sections still offset · inserted ${wantI.toFixed(2)} ± .15 @ ${elI.toFixed(0)} ms`, `${gone.length ? cs(gone[0]).opacity : "no clone"} · ${moved.length} moving · ${insR.length} fading in ${insR.length ? insR[0].style.opacity : ""}`, gone.length > 0 && parseFloat(cs(gone[0]).opacity) <= 0.12 && moved.length > 0 && (insR.length > 0 ? Math.abs(parseFloat(insR[0].style.opacity) - wantI) <= .15 : wantI >= .95)); }
    await sleep(284);
    { const lr = lensNow.getBoundingClientRect(), sr = q().getBoundingClientRect(), lw = lensNow.offsetWidth, toI = parseFloat(q().style.getPropertyValue("--i")), fromI = toI === 1 ? 0 : 1;
      const segW = (sr.width / bs().length - 4), pos = (lr.left + lr.width / 2 - sr.left - 2 - segW / 2) / segW;   // centre-based in segment units (the lens now moves by `left`, its width breathes)
      num("分段 G1 抬手 +556 ms：透镜在目标外过冲途中（原生 seg-native-tap-frames.json up+.553 中心 307.55 → 行程 1.038；换值弹簧 ζ.85/.4 + flex 漂移）", 1.038, (pos - fromI) / (toI - fromI), 0.05); }
    check("分段 B3 +476 ms：内容过渡收尾（+400 到位 → 克隆移除、transform / opacity 内联清空）", "clean", `${document.querySelectorAll(".flipgone").length} clones · ${[...document.querySelectorAll("#app > section, #app .row")].filter((e) => e.style.transform || e.style.opacity).length} inline`, !document.querySelectorAll(".flipgone").length && ![...document.querySelectorAll("#app > section, #app .row")].some((e) => e.style.transform || e.style.opacity));
    { const L = await window.__r20cLater; check("R20c 换值 +260 ms：位图已撤、真字恢复（颜色非透明、字重 = 选中 .on 的 medium；真字自己的过渡未完则等它结束，报多等的 ms）", "0 ghosts · real text", `${L.left} ghosts · color ${L.color} · weight ${L.weight}${L.late ? " · waited +" + L.late + " ms" : ""}`, L.left === 0 && L.color !== "rgba(0, 0, 0, 0)" && parseInt(L.weight) >= 500); }
    await segRest(800);   // S1: the lens loop's own "done" (≤ the old 800)
    /* §1 G4/G16: touch-down on the selected segment lifts the lens after ~100 ms (196×28 → 220×44), no event */
    seg = q(); let sel = bs().find((b) => b.classList.contains("on")), unsel = bs().find((b) => !b.classList.contains("on"));
    const r1 = R.n; pev(seg, "pointerdown", at(sel)); const lens0 = seg.querySelector(".lens");
    check("分段 G4 按下已选中段：+0 ms 透镜未抬、无事件", "no lift", lens0.classList.contains("lift") ? "lift" : "no lift", !lens0.classList.contains("lift") && R.n === r1);
    await sleep(160);
    const h160 = lens0.getBoundingClientRect().height;
    check("分段 G16 按下已选中段 +160 ms：透镜抬起中（+109 ms 起，--ios-motion-seg-lift-easing .35 s 到 220×44；seg-lens-refraction §4.1）", "lift, 28 < h < 44", `${lens0.classList.contains("lift") ? "lift" : "-"} h ${h160.toFixed(1)}`, lens0.classList.contains("lift") && h160 > 28.5 && h160 < 43.5);
    /* lifted lens = glass ABOVE the labels + punched-out labels + a warped copy inside (uiprobe-lensdiff-seg: ClearGlassView / DestOutView /
       liftedContentWarpWrapper); --lp on the lenstrace curve (lens-refraction §4.1: 86 % at 153 ms) drives glass + warp */
    const GLON = seg.classList.contains("gl");   // WebGL lens (view.js segGlCreate, lens-webgl.js): the SVG stack is built but hidden — its checks are recorded, not judged
    const svgcheck = GLON ? (() => {}) : check, svgnum = GLON ? (() => {}) : num;   // S5: under GL the SVG stack is hidden — no placeholder rows (8 rows that always passed); in SVG mode (?gl=0) the real checks
    { const lp = parseFloat(seg.style.getPropertyValue("--lp")), warp = seg.querySelector(".warp"), warpl = seg.querySelector(".warpl"), cb = warpl ? warpl.querySelectorAll(".copy .cb").length : 0;
      check("分段抬起 +160 ms：玻璃/位移进度 --lp = 透镜尺寸进度（§4.1：尺寸、圆角、位移量、白平台同一条曲线）", "0 < lp < 1, = (h−28)/16", `${lp} vs ${((lens0.getBoundingClientRect().height - 28) / 16).toFixed(3)}`, lp > 0 && lp < 1 && Math.abs(lp - (lens0.getBoundingClientRect().height - 28) / 16) < 0.12);
      svgcheck("分段抬起：透镜层在标签之上（z 2）", "2", cs(lens0).zIndex, cs(lens0).zIndex === "2" && seg.classList.contains("lift"));
      { const br = px(cs(lens0).borderRadius), hh = lens0.getBoundingClientRect().height; check("分段抬起：几何走 width/height（真胶囊：圆角 = 高/2，14 → 22 与尺寸同曲线；seg-lens-refraction §0 220×44 r22）", "r ≈ h/2", `r ${br.toFixed(1)} h ${hh.toFixed(1)}`, Math.abs(br - hh / 2) < 1.2 && cs(lens0).scale === "1"); }
      { const punch = warp && warp.querySelector(".disp .punch"), pcp = punch && punch.querySelector(".copy .cb"), SSa = window.LENS_SS || 1;   // 引擎校正 2 (lens-supersample.js): the filtered layer is SS× the box inside a wrapper scaled 1/SS
        svgcheck("分段抬起：底图复本 .warp 过 #seg-lens-f-bg-220、标签复本 .warpl 过 #seg-lens-f-lab-220（220 组，滤镜层 = 透镜盒 overflow hidden ← ui2 README §0.3）；B4-c' §4b：标签复本 = 整盒先裁胶囊再位移、无 196×28 门户；底图复本带 .punch（标签复本挖掉胶囊 = DestOut，clip-path evenodd）", `${bs().length} cb · disp url(#seg-lens-f-bg-220) · displ url(#seg-lens-f-lab-220) · no .portal · punch evenodd`, `${cb} cb · ${warp ? cs(warp.querySelector(".disp")).filter.slice(0, 26) : "-"} · ${warpl ? cs(warpl.querySelector(".displ")).filter.slice(0, 27) : "-"} · ${warpl && warpl.querySelector(".portal") ? "portal!" : "no .portal"} · ${punch ? (cs(punch).clipPath.startsWith("path(evenodd") ? "punch evenodd" : cs(punch).clipPath.slice(0, 20)) : "no punch"} ${pcp ? "+labels" : ""}`, !!warp && !!warpl && cb === bs().length && bs().length === 2 && /inset/.test(cs(warp).clipPath) && /inset/.test(cs(warpl).clipPath) && /url\("?#seg-lens-f-bg-220"?\)/.test(cs(warp.querySelector(".disp")).filter) && cs(warp.querySelector(".disp")).overflow === "hidden" && Math.abs(warp.querySelector(".disp").getBoundingClientRect().width - warp.getBoundingClientRect().width) < 0.5 && Math.abs(warp.querySelector(".disp").offsetWidth - SSa * warp.getBoundingClientRect().width) < 1 && /url\("?#seg-lens-f-lab-220"?\)/.test(cs(warpl.querySelector(".displ")).filter) && !warpl.querySelector(".portal") && Math.abs(px(cs(warpl.querySelector(".displ")).borderRadius) - SSa * warpl.getBoundingClientRect().height / 2) < 1.5 * SSa && !!punch && cs(punch).clipPath.startsWith("path(evenodd") && !!pcp); }
      { const cp = warp && warp.querySelector(".copy"), cpl = warpl && warpl.querySelector(".copy"), bgw = cp && cp.querySelector(".cbgwrap");
        check("分段抬起：复本不放大（mag-x 1.00 / label-mag 1.00，zoom 1）、底不透明、底不过色矩阵（透镜内亮度 = 底）", "zoom 1 · opaque · no filter", `${cp ? cs(cp).zoom : "-"} / ${cpl ? cs(cpl).zoom : "-"} · bg ${cs(cp.querySelector(".cbg")).backgroundColor.slice(0, 4)} · ${bgw ? cs(bgw).filter : "-"}`, !!cp && !!cpl && cs(cp).zoom === "1" && cs(cpl).zoom === "1" && /^rgb\(/.test(cs(cp.querySelector(".cbg")).backgroundColor) && !!bgw && cs(bgw).filter === "none" && !!cp.querySelector(".cbgwrap .ctrack"));   // cp = the first .copy of .warp (the page + track one)
        const fd = document.querySelector("#seg-lens-f-bg-220 feDisplacementMap"); svgcheck("分段抬起：位移量 scale = S × SS × 进度（S = 该组 filter 的 data-s0 / data-s，220 组 40 ← ui2 c4efe4b；SS = 引擎校正 2 的倍数 window.LENS_SS，lens-supersample.js 把 data-s 写成 S × SS；同一条曲线）", `≈ 40·${window.LENS_SS || 1}·lp`, `${fd ? fd.getAttribute("scale") : "-"} (data-s ${document.querySelector("#seg-lens-f-bg-220").getAttribute("data-s")})`, !!fd && (document.querySelector("#seg-lens-f-bg-220").getAttribute("data-s0") || document.querySelector("#seg-lens-f-bg-220").getAttribute("data-s")) === "40" && Math.abs(parseFloat(fd.getAttribute("scale")) - 40 * (window.LENS_SS || 1) * lp) < 0.8 * (window.LENS_SS || 1));
        const pl = seg.querySelector(".plat"); check("分段抬起：白平台层 .plat 在底复本之上、标签复本之下（z 5 / 7；B6 的 .rimb 在两者之间 z 6），opacity = 1 − lp（restingBackground 1 → 0，seg-keys -platter-keys）；底复本 opacity = DestOut（前 3 帧到 1，-destout-keys）；标签复本不淡", "1−lp · warp 1 · warpl 1 · z 5/7", `${pl ? cs(pl).opacity : "-"} · ${cs(warp).opacity} · ${cs(warpl).opacity} · z ${pl ? cs(pl).zIndex : "-"}/${cs(warpl).zIndex}`, !!pl && Math.abs(parseFloat(cs(pl).opacity) - (1 - lp)) < 0.03 && parseFloat(cs(warp).opacity) > 0.95 && cs(warpl).opacity === "1" && cs(pl).zIndex === "5" && cs(warpl).zIndex === "7"); }
      if (warp) { const wr = warp.getBoundingClientRect(), lr = lens0.getBoundingClientRect();
        svgnum("分段抬起：复本框 = 透镜呈现框（左）", lr.left, wr.left, 0.6); svgnum("分段抬起：复本框 = 透镜呈现框（宽）", lr.width, wr.width, 0.6); }
      check("分段抬起：真标签不挖洞（不透明复本盖住 = DestOut 冲掉的视觉），透镜层自身不画阴影（B6：无 ::after、无 box-shadow）", "no mask · none", `${cs(sel).maskImage} · ${cs(lens0, "::after").content} ${cs(lens0).boxShadow}`, cs(sel).maskImage === "none" && cs(lens0, "::after").content === "none" && cs(lens0).boxShadow === "none"); }
    await sleep(240);
    { const r4 = lens0.getBoundingClientRect(), segW = seg.getBoundingClientRect().width / bs().length - 4;
      check("分段 G16 +400 ms：透镜到 220×44（段宽 + 24 × 44；几何 +359 ms 到位 ← seg-lens-refraction §4.1；--ios-touch-segment-lift-x 12 / -y 8）", `${(segW + 24).toFixed(1)}×44`, `${r4.width.toFixed(1)}×${r4.height.toFixed(1)}`, Math.abs(r4.width - (segW + 24)) < 0.8 && Math.abs(r4.height - 44) < 0.8); }
    check("分段抬起 +400 ms：--lp 到 1", "≈ 1", seg.style.getPropertyValue("--lp"), parseFloat(seg.style.getPropertyValue("--lp")) > 0.97);
    /* B6: the lifted lens's lines and shadows from the decompiled formulas (index.html "B6" block, view.js SEG_RIM; keyfill-highlight.md §2 / §4 / §5.1 / §5.2, keys seg-lens-refraction.md §1c(g)) */
    { svgcheck("分段抬起满：透镜内亮度 = 底（seg-lens-refraction §3 平灰 128 → 126：可见层不套 vibrantColorMatrix、不模糊）", "no filter", (cs(lens0).backdropFilter || "none") + " · " + cs(seg.querySelector(".warp .disp")).filter.slice(0, 26), (cs(lens0).backdropFilter || "none") === "none" && /url/.test(cs(seg.querySelector(".warp .disp")).filter));
      const rb = seg.querySelector(".rimb"), hlAll = [...seg.querySelectorAll(".hlk, .hlw")], hk = seg.querySelector(".hlk.m"), hw = seg.querySelector(".hlw.m"), lpNow = parseFloat(seg.style.getPropertyValue("--lp"));
      check("分段抬起满 B6：边线分两层——.rimb（标签复本之下 z 6：内阴影 + ring shadow + 外侧暗线）、.hlk/.hlw（之上 z 8：高光黑栈 / 白 plus-lighter 栈，三次合成的顺序 = 黑主带、白主带、黑漫射、白漫射），随 --lp 淡入", "z 6 / 8 · k.m w.m k.d w.d · plus-lighter · lp", `z ${rb ? cs(rb).zIndex : "-"} / ${hk ? cs(hk).zIndex : "-"} · ${hlAll.map((e) => e.getAttribute("class").replace(/^hl/, "").split(" ").join(".")).join(" ")} · ${hw ? cs(hw).mixBlendMode : "-"} · ${hw ? cs(hw).opacity : "-"}`, !!rb && !!hk && !!hw && cs(rb).zIndex === "6" && hlAll.length === 4 && hlAll.every((e) => cs(e).zIndex === "8") && hlAll.map((e) => e.getAttribute("class")).join("|") === "hlk m|hlw m|hlk d|hlw d" && cs(hw).mixBlendMode === "plus-lighter" && cs(hk).mixBlendMode === "normal" && Math.abs(parseFloat(cs(hw).opacity) - lpNow) < 0.03 && Math.abs(parseFloat(cs(rb.firstElementChild).opacity) - lpNow) < 0.03);
      const ish = rb && rb.querySelector(".ish"), rs = rb && rb.querySelector("rect.rs"), kfs = rb ? [...rb.querySelectorAll("rect.kf")] : [];
      { const f = document.querySelector("#seg-lens-f-ish"), off = f && f.querySelector("feOffset"), bl = f && f.querySelector("feGaussianBlur"), fa = f && f.querySelector("feFuncA");
        check("分段抬起满 B6 ④：内阴影 #21 = op·M·blur_σ3(M − M↓7)（keyfill §5.2c，2号 #seg-lens-f-ish：feOffset 7 → out → blur 3 → in → α × .06，黑胶囊 = 透镜盒；dy / σ / slope 随 --lp）", `filter #seg-lens-f-ish · bg #000 · dy ${(7 * lpNow).toFixed(2)} σ ${(3 * lpNow).toFixed(2)} slope ${(.06 * lpNow).toFixed(3)}`, ish ? `${cs(ish).filter.slice(0, 24)} · ${cs(ish).backgroundColor} · dy ${off ? off.getAttribute("dy") : "-"} σ ${bl ? bl.getAttribute("stdDeviation") : "-"} slope ${fa ? fa.getAttribute("slope") : "-"}` : "no .ish", !!ish && /seg-lens-f-ish/.test(cs(ish).filter) && cs(ish).backgroundColor === "rgb(0, 0, 0)" && !!off && Math.abs(parseFloat(off.getAttribute("dy")) - 7 * lpNow) < 0.1 && Math.abs(parseFloat(bl.getAttribute("stdDeviation")) - 3 * lpNow) < 0.05 && Math.abs(parseFloat(fa.getAttribute("slope")) - .06 * lpNow) < 0.002); }
      svgcheck("分段抬起满 B6 ③：ring shadow = 胶囊下移 8、内缩 2 的 4 宽描边 黑 .1 + feGaussianBlur 3（keys offset 8 / opacity .1 / stroke 4 / blur 3 / mask 0）", "y 10 · x 2 · rx h/2 − 2 · sw 4 · .1 · blur", rs ? `y ${rs.getAttribute("y")} x ${rs.getAttribute("x")} rx ${parseFloat(rs.getAttribute("rx")).toFixed(2)} · sw ${cs(rs).strokeWidth} · ${cs(rs).strokeOpacity} · ${cs(rs).filter.slice(0, 20)}` : "-", !!rs && rs.getAttribute("y") === "10" && rs.getAttribute("x") === "2" && Math.abs(parseFloat(rs.getAttribute("rx")) - (lens0.getBoundingClientRect().height / 2 - 2)) < 0.15 && cs(rs).strokeWidth === "4px" && cs(rs).strokeOpacity === "0.1" && /url/.test(cs(rs).filter) && rb.querySelector("feGaussianBlur").getAttribute("stdDeviation") === "3");
      const darkT = matchMedia("(prefers-color-scheme: dark)").matches || document.documentElement.dataset.theme === "dark", expA = darkT ? [0.728, 0.520, 0.312] : [0.317, 0.226, 0.136];   // B6-c §1: k_tip = v (.875 / .625 / .375), × .3 × (3 − 2B_track) (light B ≈ .897 → 1.206; dark ≈ .114 → 2.773)
      const kfa = kfs.map((k) => parseFloat(k.getAttribute("stroke-opacity"))), kfW = kfs.map((k) => parseFloat(k.getAttribute("stroke-width"))), kfY = kfs.map((k) => parseFloat(k.getAttribute("y")));
      svgcheck("分段抬起满 B6 ②：外侧暗线 = 三个 1/3 pt 描边环（中线 y −.5 / −.167 / +.167：胶囊外 .667 → 内 .333），黑 α = .3·k_tip·(3 − 2B_track)（k_tip = v .875 / .625 / .375，B6-c §1 去压缩；" + (darkT ? "暗 B ≈ 29/255" : "亮 B ≈ 229/255") + "），横向渐变 = k(x)/k_tip、纵向遮罩 = 页面因子", `3 rings · α ≈ ${expA.join("/")} · y −.5/−.167/.167 · gradient + mask`, `${kfs.length} rings · α ${kfa.map((x) => x.toFixed(3)).join("/")} · y ${kfY.map((x) => x.toFixed(3)).join("/")} · w ${kfW.map((x) => x.toFixed(3)).join("/")} · ${kfs.length && /url/.test(kfs[0].getAttribute("stroke")) ? "gradient" : "-"} ${kfs.length && kfs[0].parentElement.getAttribute("mask") ? "mask" : "-"}`,
        kfs.length === 3 && kfa.every((x, n) => Math.abs(x - expA[n]) < 0.012) && kfY.every((y, n) => Math.abs(y - [-0.5, -1 / 6, 1 / 6][n]) < 0.001) && kfW.every((w) => Math.abs(w - 1 / 3) < 0.001) && kfs.every((k) => /url/.test(k.getAttribute("stroke"))) && !!kfs[0].parentElement.getAttribute("mask"));
      const hkR = hk ? [...hk.querySelectorAll("line")] : [], hwR = hw ? [...hw.querySelectorAll("line")] : [], hdR = [...seg.querySelectorAll(".hlk.d rect")], hdW = [...seg.querySelectorAll(".hlw.d rect")];
      svgcheck("分段抬起满 B6 ①：内侧亮线 + 高光尾 = #36 层公式：黑栈 stroke-opacity .0882·α / 白栈 .1471·α，主带 3 环 × 上下两条直线（B6-c §4b：只画直边 x ∈ [R, W−R]，纯色；首环 α .875）+ 漫射 10 环（首环 .803，渐变描边）", "6+6 lines · 10+10 · .0772/.1287 · .0708/.1181 · x1 R x2 W−R", `${hkR.length}+${hwR.length} · ${hdR.length}+${hdW.length} · ${hkR.length ? hkR[0].getAttribute("stroke-opacity") : "-"}/${hwR.length ? hwR[0].getAttribute("stroke-opacity") : "-"} · ${hdR.length ? hdR[0].getAttribute("stroke-opacity") : "-"}/${hdW.length ? hdW[0].getAttribute("stroke-opacity") : "-"} · ${hkR.length ? `x1 ${hkR[0].getAttribute("x1")} x2 ${hkR[0].getAttribute("x2")} ${hkR[0].getAttribute("stroke")}` : "-"}`,
        hkR.length === 6 && hwR.length === 6 && hdR.length === 10 && hdW.length === 10 && Math.abs(parseFloat(hkR[0].getAttribute("stroke-opacity")) - 0.0882 * 0.875) < 0.001 && Math.abs(parseFloat(hwR[0].getAttribute("stroke-opacity")) - 0.1471 * 0.875) < 0.001 && Math.abs(parseFloat(hdR[0].getAttribute("stroke-opacity")) - 0.0882 * 0.803) < 0.001 && Math.abs(parseFloat(hdW[0].getAttribute("stroke-opacity")) - 0.1471 * 0.803) < 0.001 && hkR.every((l) => l.getAttribute("stroke") === "#000") && hdR.every((r) => /url/.test(r.getAttribute("stroke"))) && Math.abs(parseFloat(hkR[0].getAttribute("stroke-width")) - 1 / 3) < 0.001 && Math.abs(parseFloat(hkR[0].getAttribute("x1")) - lens0.getBoundingClientRect().height / 2) < 0.6 && Math.abs(parseFloat(hkR[0].getAttribute("x2")) - (lens0.getBoundingClientRect().width - lens0.getBoundingClientRect().height / 2)) < 0.6);
      if (GLON) { const c = seg.querySelector("canvas.glens"), g = seg.__gl, sr = seg.getBoundingClientRect(), cr = c && c.getBoundingClientRect(), lr = lens0.getBoundingClientRect(), fr0 = g ? g.lens.stats.frames : 0, F1 = window.LensWebGL ? LensWebGL.FS1 + LensWebGL.FS2 + LensWebGL.COMMON : "";
        check("分段 WebGL：canvas.glens 盖住控件 ± 24 pt（宽 = 控件，高 = 控件 + 48；README §0.8.7：包裹 = 透镜 ± 16 + 抬起外扩 6，环影下延 11），指针穿透，z 9", "box = seg ± 24 · pointer-events none · z 9", c ? `dx ${(cr.left - sr.left).toFixed(1)} dy ${(cr.top - sr.top).toFixed(1)} w ${(cr.width - sr.width).toFixed(1)} h ${(cr.height - sr.height).toFixed(1)} · ${cs(c).pointerEvents} · z ${c.parentElement && c.parentElement.classList.contains("lens-clip") ? cs(c.parentElement).zIndex + "（裁框）" : cs(c).zIndex}` : "no canvas", !!c && Math.abs(cr.left - sr.left) < .6 && Math.abs(cr.top - sr.top + 24) < .6 && Math.abs(cr.width - sr.width) < .6 && Math.abs(cr.height - sr.height - 48) < .6 && cs(c).pointerEvents === "none" && (c.parentElement && c.parentElement.classList.contains("lens-clip") ? cs(c.parentElement).zIndex : cs(c).zIndex) === "9");   // R96: the z-index moved to the canvas's .lens-clip wrapper (2号)
        check("分段 WebGL：LensWebGL 实例走 220 组（README §0.3：抬起与拖动都在模型宽的那组），有帧在画（stats.frames 递增、set 220）", "set 220 · frames > 0", g ? `set ${g.lens.stats.set} · frames ${g.lens.stats.frames} · gpu ${g.lens.stats.gpuMs.toFixed(2)} ms` : "no instance", !!g && g.lens.stats.set === 220 && g.lens.stats.frames > 0);
        /* R31 (2号 lens-webgl.js): the labels texture for a selection is prepared at idle and switched at the down without a redraw — the API row: a variant
           prepared (seg:gl-prepare measured once), useLabels binds it with no seg:gl-redraw measure and no frame; an unknown key returns false */
        if (g && typeof g.lens.prepareLabels === "function") { const meas = (n) => performance.getEntriesByType("measure").filter((m) => m.name === n).length;
          const p0 = meas("seg:gl-prepare"), r0 = meas("seg:gl-redraw") + meas("seg:gl-redraw-task"), f0 = g.lens.stats.frames;
          const okP = g.lens.prepareLabels("accept", (x, info) => { x.fillStyle = "#000"; x.font = "bold 13px -apple-system"; x.fillText("R31", info.region.x + 10, info.region.y + 40); });
          const okU = g.lens.useLabels("accept"); const r1 = meas("seg:gl-redraw") + meas("seg:gl-redraw-task"), f1 = g.lens.stats.frames;
          check("分段 WebGL R31：标签纹理按选中预备（prepareLabels 一次 seg:gl-prepare）、按下只切绑定（useLabels 无 seg:gl-redraw、不画帧）、未知键 false", "prepare 1 · use true · redraw +0 · frames +0 · unknown false", `prepare ${meas("seg:gl-prepare") - p0} · use ${okU} · redraw +${r1 - r0} · frames +${f1 - f0} · unknown ${g.lens.useLabels("no-such")}`, okP && okU && meas("seg:gl-prepare") - p0 === 1 && r1 - r0 === 0 && f1 - f0 === 0 && !g.lens.hasLabels("no-such"));
          g.lens.redrawNow(); }   // back to the live labels (a redraw drops the variants)
        /* R37 (2号): the label copy's field is evaluated per pixel in float from the decoded stages (formula §1 / §2 composed as compose_stages; no 8-bit map) — the
           stages and the capsule radius the shader is given are the read values (seg-lens-refraction.md §1b 表 1 #18 / #30: ContentLensing −8.8 / 7.04 then ClearGlass −17.5 / 11.2;
           r 22); the harness numbers (README §0.8.14) are the Mac's, the device's saturation is the phone's to read */
        if (g && g.lens.stats.labMode) { const st = g.lens.stats; const okS = Array.isArray(st.labelStages) && st.labelStages.join(",") === "-8.8,7.04,-17.5,11.2";
          check("分段 WebGL R37：标签复本场在着色器里按式逐像素算（closed；?gllab=map 回贴图）、两级键 = 读数、胶囊 r 22", "closed · −8.8/7.04,−17.5/11.2 · r 22", `${st.labMode} · ${(st.labelStages || []).join("/")} · r ${st.rmax}`, st.labMode === "closed" && okS && st.rmax === 22);
          /* R38a: the element SDF of the label field — QuartzCore's supercircle branch (§7 ② / §7b (a′)) is in the shader behind ?glsdf=super / opts.labelSdf; the
             default stays the capsule (待澄清: on the label stages the supercircle takes the end ink 81 → 79 % in the closed form, the native is 68 %) */
          const fs1 = (window.LensWebGL && LensWebGL.FS1) || "";
          check("分段 WebGL R38a：超圆 SDF（1.528665·r、clamp sat(2.89158·(1 − hs/r))、poly 五次）在着色器里，默认 circle（?glsdf=super 切）", "circle · sdfSuper 在", `${st.labelSdf} · ${/sdfSuper/.test(fs1) && /1\.528665/.test(fs1) && /2\.89158/.test(fs1) && /0\.268531/.test(fs1) ? "sdfSuper 在" : "缺"}`, st.labelSdf === "circle" && /sdfSuper/.test(fs1) && /1\.528665/.test(fs1) && /2\.89158/.test(fs1) && /0\.268531/.test(fs1));
          /* R38″ (§5d): the portal composite's three items do nothing to the copy — here the copy term lab(ql)·Ml·B carries no DestOut (u_pd acts on the source labels in the
             backdrop copy only) and no opacity factor */
          const lcLine = (fs1.match(/vec4 lc = [^;]+;/) || [""])[0], bgcLine = (fs1.match(/vec4 bgc = [^;]+;/) || [""])[0];
          check("分段 WebGL R38″：复本无 DestOut、opacity ×1（lc 项无 u_pd；u_pd 只在底图复本的源标签上）", "lc 无 u_pd · bgc 有 u_pd", `lc ${/u_pd/.test(lcLine) ? "有" : "无"} u_pd · bgc ${/u_pd/.test(bgcLine) ? "有" : "无"} u_pd`, !!lcLine && !/u_pd/.test(lcLine) && /u_pd/.test(bgcLine)); }
        check("分段 WebGL：flex 变换加在 canvas 上、原点 = 透镜中心（canvas 坐标 = 透镜盒中心 + 24 pt）", "origin = lens centre", c ? `${c.style.transformOrigin || "-"} vs ${(lr.left - sr.left + lr.width / 2).toFixed(1)}px ${(lr.top - sr.top + 24 + lr.height / 2).toFixed(1)}px` : "-", !!c && (() => { const m = /([\d.]+)px ([\d.]+)px/.exec(c.style.transformOrigin || ""); return !!m && Math.abs(parseFloat(m[1]) - (lr.left - sr.left + lr.width / 2)) < 1.5 && Math.abs(parseFloat(m[2]) - (lr.top - sr.top + 24 + lr.height / 2)) < 1.5; })());
        check("分段 WebGL：白平台淡出在 shader 里（dc2af2a u_platter：位移底图之上、边线/标签之下，alpha 1 − p，_controlForegroundColor 令牌），.lens 抬起时透明如 SVG 路径", "u_platter · .lens transparent z 2", `${F1 && F1.includes("u_platter") ? "u_platter" : "no u_platter"} · ${cs(lens0).backgroundColor} z ${cs(lens0).zIndex}`, !!F1 && F1.includes("u_platter") && /rgba\(0, 0, 0, 0\)|transparent/.test(cs(lens0).backgroundColor) && cs(lens0).zIndex === "2");
        check("分段 WebGL：SVG 栈隐藏（.stack / .rimo / .hlk / .hlw display none）", "none ×4", [".stack", ".rimo", ".hlk", ".hlw"].map((q) => { const e = seg.querySelector(q); return e ? cs(e).display : "-"; }).join(" "), [".stack", ".rimo", ".hlk", ".hlw"].every((q) => { const e = seg.querySelector(q); return !e || cs(e).display === "none"; }));
        check("分段 WebGL：着色器里是反编译常量（暗线 EffectOffset −.6667 / colorBias −.3、vibrant V = min(1, .9118·b + .1471)、环影 8 / 4 / σ3 / .1；色散 Δ 与 aberration 2.3158 在贴图里）", "all present", ["0.6667", "-0.3", "0.9118", "0.1471"].map((k) => (F1.includes(k) ? "✓" : "✗") + k).join(" "), ["0.6667", "-0.3", "0.9118", "0.1471"].every((k) => F1.includes(k))); }
      check("分段抬起满 B6：不再有采样剖面（--seg-rim-* 渐变、半圆帽、11 px 暗带、透镜 box-shadow 实心影）", "gone", `${getComputedStyle(document.documentElement).getPropertyValue("--seg-rim-top") ? "rim-top" : "-"} ${seg.querySelector(".capL") ? "capL" : "-"} ${cs(lens0).boxShadow}`, !getComputedStyle(document.documentElement).getPropertyValue("--seg-rim-top") && !seg.querySelector(".capL") && cs(lens0).boxShadow === "none"); }
    /* §1 G4/G22: sliding onto the other segment moves the lens, the index does not change until the up */
    { const a0 = at(sel), a1 = at(unsel), lensD = seg.querySelector(".lens"); let wMax = 0, hMin = 99;
      for (let k = 1; k <= 10; k++) { pev(seg, "pointermove", { x: a0.x + (a1.x - a0.x) * k / 10, y: a1.y }); /* at() returns {x, y}; the old array form gave clientX 0 (the far left) and only the hard clamp made the check pass */ await sleep(16); const r = lensD.getBoundingClientRect(); wMax = Math.max(wMax, r.width); hMin = Math.min(hMin, r.height); }   // the native abc recording: 10 × 20 pt every ~17 ms
      for (let k = 0; k < 6; k++) { await sleep(16); const r = lensD.getBoundingClientRect(); wMax = Math.max(wMax, r.width); hMin = Math.min(hMin, r.height); }
      check("分段 G22 按住滑到另一段：透镜跟手（模型位置 ζ.85/.2 → 呈现跟踪 ζ.6533/.4559，seg-lens-refraction §4.4 原值）；跟手中拉长、变矮（占位：B 段逐帧表回放，等原理）", "w > 232 · h < 40", `w ${wMax.toFixed(1)} · h ${hMin.toFixed(1)}`, wMax > 232 && hMin < 40);
      await sleep(300); const lr = lensD.getBoundingClientRect(), ur = unsel.getBoundingClientRect();
      check("分段 G22 按住滑到另一段 +400 ms：透镜到手指下（呈现中心 = 位置弹簧过冲 + flex drift，原生 B 段过冲 10 pt；本页位置弹簧多过冲 ~4 pt（B2-a 已知差），容 ± 16）、index 不改", `${onText()} centre ${(ur.left + ur.width / 2).toFixed(0)}`, `${onText()} centre ${(lr.left + lr.width / 2).toFixed(1)} ${lr.width.toFixed(1)}×${lr.height.toFixed(1)}`, onText() === sel.textContent && Math.abs(lr.left + lr.width / 2 - (ur.left + ur.width / 2)) < 16 && R.n === r1);
      await sleep(500); { const lr2 = lensD.getBoundingClientRect(); check("分段 G22 按住滑到另一段 +900 ms：透镜落定在手指下（中心 ± 3 pt）、220×44（flex 随位置弹簧余动仍在收敛，容 ± 3）", `centre ${(ur.left + ur.width / 2).toFixed(0)} · ${((seg.getBoundingClientRect().width / bs().length - 4) + 24).toFixed(0)}×44`, `centre ${(lr2.left + lr2.width / 2).toFixed(1)} · ${lr2.width.toFixed(1)}×${lr2.height.toFixed(1)}`, Math.abs(lr2.left + lr2.width / 2 - (ur.left + ur.width / 2)) < 3 && Math.abs(lr2.height - 44) < 1.5 && Math.abs(lr2.width - ((seg.getBoundingClientRect().width / bs().length - 4) + 24)) < 3); } }
    /* §1 G23: slide back and release on the original - no event */
    pev(seg, "pointermove", at(sel)); pev(seg, "pointerup", at(sel));
    check("分段 G23 滑回原段抬手：无事件，透镜回位", sel.textContent, `${onText()} renders+${R.n - r1}`, onText() === sel.textContent && R.n === r1 && q().style.getPropertyValue("--i") === String(bs().indexOf(sel)));
    await sleep(120); { const lp = parseFloat(seg.style.getPropertyValue("--lp")), hr = seg.querySelector(".lens").getBoundingClientRect().height; check("分段松手 +120 ms：几何从 +31 ms 起沿 ζ1/.25 弹簧回落（§4.4 落回几何；途中 28 < h < 44）；材质沿 ζ1/.4 退回（§4.4 落回材质；+89 ms 剩 ≈ .59）", "29 < h < 43 · .45 < lp < .75", `h ${hr.toFixed(1)} · lp ${lp}`, hr > 29 && hr < 43 && lp > 0.45 && lp < 0.75); }
    await sleep(200); { const lr = seg.querySelector(".lens").getBoundingClientRect(), sr = seg.getBoundingClientRect(); check("分段松手 +320 ms：模型尺寸回到 196×28（ζ1/.25：+289 ms 达 99.4 %），呈现上还叠着 flex 的松手回弹（原生 C 段 +308 196.9×28.1，本页更大），容 ± 10 %", `${((sr.width / bs().length - 4)).toFixed(1)}×28 ±10%`, `${lr.width.toFixed(1)}×${lr.height.toFixed(1)}`, Math.abs(lr.height - 28) < 2.8 && Math.abs(lr.width - (sr.width / bs().length - 4)) < 19.6); }
    await segRest(1180); { const lr = seg.querySelector(".lens").getBoundingClientRect(), sr = seg.getBoundingClientRect(); check("分段松手 落定（驱动器 done，≤ 1.5 s）：位置落定回原段（行程 ζ.85/.4 → 跟踪 ζ.56/.444，§4.4）、玻璃退净、复本收起、透镜内联几何清掉", "rest · no inline · at rest left", `${seg.classList.contains("lift") ? "lift" : "rest"} ${seg.style.getPropertyValue("--lp") || "-"} · ${seg.querySelector(".lens").style.width || "no inline"} · ${lr.left.toFixed(1)}`, !seg.classList.contains("lift") && !seg.querySelector(".lens").style.width && Math.abs(lr.left - (sr.left + 2 + bs().indexOf(sel) * (sr.width / bs().length))) < 0.6); }
    /* acceptance requirement 4: pointercancel after a lift → glass + warp fall on the same curve, never a cut */
    { const sg = q(), on = bs().find((b) => b.classList.contains("on")); pev(sg, "pointerdown", at(on)); await sleep(360); const lpUp = parseFloat(sg.style.getPropertyValue("--lp"));
      pev(sg, "pointercancel", at(on)); await sleep(60); const lp60 = parseFloat(sg.style.getPropertyValue("--lp"));
      check("分段 pointercancel：玻璃/折弯沿同曲线退回（+60 ms 仍在途中，不瞬切）", "lift 1 → 0 < lp60 < lpUp", `${lpUp} → ${lp60}`, lpUp > 0.95 && lp60 > 0.05 && lp60 < lpUp);
      await segRest(640); check("分段 pointercancel 落定（驱动器 done，≤ 700 ms）：退净", "rest", sg.classList.contains("lift") ? "lift" : "rest", !sg.classList.contains("lift")); }
    /* §1 G4/G21: lift, slide to the other segment, release there - commits at the up */
    seg = q(); sel = bs().find((b) => b.classList.contains("on")); unsel = bs().find((b) => !b.classList.contains("on"));
    pev(seg, "pointerdown", at(sel)); await sleep(400); pev(seg, "pointermove", at(unsel)); await sleep(500); const r2 = R.n, parent0 = seg.parentNode, lens21 = seg.querySelector(".lens"); pev(seg, "pointerup", at(unsel)); const q21 = document.querySelector("#queue").value; await sleep(60);
    check("分段 G21 抬起后滑到另一段抬手：选中那段（模型在抬手即改，内容 +25 ms 切 ← --seg-commit-delay-drag；vcsplit 重画在其后一帧，+60 ms 看）", unsel.textContent, `${onText()} model ${q21}`, q21 === unsel.dataset.q && onText() === unsel.textContent && thisShift(unsel.textContent) && R.n === r2 + 1);
    check("分段 G21 换值重画：#queueseg 及其父节点原地保留（replaceKeeping，不摘下再插回 → 过渡不被取消；B2-b）", "same node · same parent", `${q() === seg ? "same node" : "new node"} · ${q().parentNode === parent0 ? "same parent" : "new parent"}`, q() === seg && q().parentNode === parent0);
    { const h1 = lens21.getBoundingClientRect().height; await sleep(16); const h2 = lens21.getBoundingClientRect().height;
      check("分段 G21 松手 +1 帧：透镜仍是抬起尺寸、随后逐帧回落（B2-b：不瞬回 28）", "h ≥ 39 at +0, > 36 at +16 ms", `${h1.toFixed(1)} → ${h2.toFixed(1)}`, h1 >= 39 && h2 > 36); }
    await sleep(200); { const lr = lens21.getBoundingClientRect(); check("分段 G21 松手 +216 ms：几何回落途中，叠着 flex 回弹（原生 C 段 +204 ms h 31.8；B5 后本页 24 < h < 40）", "24 < h < 40", lr.height.toFixed(1), lr.height > 24 && lr.height < 40); }
    await segRest(600); { const lr = lens21.getBoundingClientRect(), sr = seg.getBoundingClientRect(); check("分段 G21 松手 落定（驱动器 done，≤ 816 ms）：196×28 于目标段（flex 回弹收敛；位置 ζ.85/.4 → ζ.56/.444）", `196×28 at ${(sr.left + 2 + bs().indexOf(unsel) * (sr.width / bs().length)).toFixed(1)}`, `${lr.width.toFixed(1)}×${lr.height.toFixed(1)} at ${lr.left.toFixed(1)}`, Math.abs(lr.height - 28) < 0.6 && Math.abs(lr.width - (sr.width / bs().length - 4)) < 0.8 && Math.abs(lr.left - (sr.left + 2 + bs().indexOf(unsel) * (sr.width / bs().length))) < 1.5); }
    /* R7 (seg-lift-material.md §5, R15's frames): the white platter fades from the lift's first frame and its opacity = 1 − the lift progress every
       frame (+287 ms 199.1×30.1 → .8688; +304 202.8×32.5 → .7186; …; the same spring, no lag) — a press on the selected segment here, what the
       package drew each frame (stats.last) sampled for 420 ms, then released */
    { const seg7 = q(), g7 = seg7 && seg7.__gl; if (g7 && g7.lens.stats) { const selB = [...seg7.querySelectorAll("button")].find((b) => b.classList.contains("on")); const t7 = performance.now(); pev(seg7, "pointerdown", at(selB)); const r7 = [];
      await new Promise((res) => { const tick = () => { const L = g7.lens.stats.last; if (L && L.t > t7 && !(r7.length && r7[r7.length - 1].t === L.t)) r7.push({ lift: L.lift, a: L.platterAlpha, t: L.t }); if (performance.now() - t7 < 420) requestAnimationFrame(tick); else res(); }; requestAnimationFrame(tick); });
      pev(seg7, "pointerup", at(selB)); await segRest(900); delete seg7.dataset.pe;   // the browser's click would have consumed the press flag; a synthetic press leaves it, and it would eat the next real click
      const lifted = r7.filter((x) => x.lift > 0 && x.lift < 1), first = r7.find((x) => x.lift > 0), dev = lifted.map((x) => Math.abs(x.a - (1 - x.lift))), mx = dev.length ? Math.max(...dev) : NaN;
      check(`分段 R7 平台淡出：与抬起同帧起、每帧 alpha = 1 − lift（${lifted.length} 帧，最大差 ${Number.isFinite(mx) ? mx.toFixed(4) : "-"}；R15 表 .8688@p.131 / .7186@.281 / .5694@.431）`, "首抬帧 alpha < 1 · |Δ| ≤ .001 · ≥ 5 帧", first ? `首抬帧 lift ${first.lift.toFixed(3)} alpha ${first.a.toFixed(4)} · ${lifted.length} 帧` : "无抬起帧", !!first && first.a < 1 && lifted.length >= 5 && mx <= 0.001); } }
    await sleep(50);
    /* §1 G5: press the unselected one, slide onto the selected one, release - no event */
    seg = q(); sel = bs().find((b) => b.classList.contains("on")); unsel = bs().find((b) => !b.classList.contains("on"));
    const r3 = R.n; pev(seg, "pointerdown", at(unsel)); pev(seg, "pointermove", at(sel)); pev(seg, "pointerup", at(sel));
    check("分段 G5 按未选中段滑到已选中段抬手：无事件", sel.textContent, `${onText()} renders+${R.n - r3}`, onText() === sel.textContent && R.n === r3 && !unsel.classList.contains("dim"));
    /* §1 G17/G18/G26: release 60 pt below the control still selects, 100 pt below cancels (--ios-touch-inside-slop 70) */
    seg = q(); sel = bs().find((b) => b.classList.contains("on")); unsel = bs().find((b) => !b.classList.contains("on"));
    const r4 = R.n; pev(seg, "pointerdown", at(unsel)); pev(seg, "pointermove", at(unsel, .5, .5, 0, 100)); pev(seg, "pointerup", at(unsel, .5, .5, 0, 100));
    check("分段 G18 竖向滑出 100 pt 抬手：取消、无事件、标签回 1", sel.textContent, `${onText()} renders+${R.n - r4}`, onText() === sel.textContent && R.n === r4 && !unsel.classList.contains("dim"));
    seg = q(); const r5 = R.n; pev(seg, "pointerdown", at(unsel)); pev(seg, "pointermove", at(unsel, .5, .5, 0, 60)); pev(seg, "pointerup", at(unsel, .5, .5, 0, 60)); await sleep(100);
    check("分段 G17 竖向滑出 60 pt 抬手：仍选中（余量 70；内容 +66 ms 切，vcsplit 重画在其后一帧，+100 ms 看）", unsel.textContent, `${onText()} renders+${R.n - r5}`, onText() === unsel.textContent && R.n === r5 + 1);
    await sleep(50);
    /* pointercancel = cancel */
    seg = q(); sel = bs().find((b) => b.classList.contains("on")); unsel = bs().find((b) => !b.classList.contains("on"));
    const r6 = R.n; pev(seg, "pointerdown", at(unsel)); pev(seg, "pointercancel", at(unsel));
    check("分段 pointercancel：不提交、标签回 1", sel.textContent, `${onText()} renders+${R.n - r6}`, onText() === sel.textContent && R.n === r6 && !unsel.classList.contains("dim"));
    /* §1 G12/G13: ten alternating taps 30 ms down / 30 ms gap - every up counts, no debounce (--ios-touch-debounce 0) */
    const r7 = R.n; let last = null, lastQ = null, everyTick = true;
    for (let k = 0; k < 10; k++) { const b = bs()[k % 2]; last = b.textContent; lastQ = b.dataset.q; const sg = q(); pev(sg, "pointerdown", at(b)); await sleep(30); pev(sg, "pointerup", at(b)); if (document.querySelector("#queue").value !== lastQ) everyTick = false; await sleep(30); }
    await sleep(100);
    check("分段 G12 快速交替 10 次（30 ms 点 / 30 ms 间隔）：每下模型都改（抬手即改）、终态 = 最后一次；内容重画在 valueChanged 时刻，被更新的值追上的那次不再画（快速连点 未量）", last, `${onText()} renders+${R.n - r7}${everyTick ? "" : "（某下抬手时模型未改）"}`, onText() === last && R.n >= r7 + 1 && R.n <= r7 + 10 && everyTick && thisShift(last));
    let stable = true; for (let k = 0; k < 6; k++) { await sleep(100); if (onText() !== last) stable = false; }
    check("分段 G12 快速交替后 600 ms 内不回跳", last, onText(), stable && onText() === last);
    /* BOARD #9① + #9②: a quick tap on the SELECTED segment (up at 60 ms, before the 109 ms lift). 9a re-recording (seg-native-quicktap.md, run quick90c):
       the lens lifts and falls IN PLACE — first grown frame down +109, peak 217.5×42.4 at +242, back to 196×28 by +476; centre fixed; no value change.
       ① the platter is never blank: a frame with .lift must have p > 0 (the glass is drawn) — before 9① the DestOut ramp gave .lift at p = 0;
       ② geometry: the lens width / height sampled every frame against the quick90c list interpolated at the frame's time since the down. */
    await segRest(1300);   // S1: the lens loop's own "done"; the previous gesture's loop (G14's taps) has ended: the control is at rest with its opaque platter
    { const sg = q(), selB = bs().find((b) => b.classList.contains("on")), lensQ = sg.querySelector(".lens"), r9 = R.n, onIdx0 = bs().findIndex((b) => b.classList.contains("on"));
      const NAT = [[109, 198.2, 29.5], [126, 201.7, 31.8], [142, 205.3, 34.2], [159, 208.6, 36.4], [176, 211.4, 38.3], [192, 213.6, 39.7], [209, 215.3, 40.9], [227, 216.6, 41.7], [242, 217.5, 42.4], [259, 216.6, 41.8], [276, 213.8, 39.9], [292, 210.5, 37.7], [309, 207.4, 35.6], [326, 204.7, 33.8], [342, 202.5, 32.4], [359, 200.8, 31.2], [376, 199.5, 30.3], [392, 198.5, 29.7], [409, 197.8, 29.2], [426, 197.3, 28.9], [442, 196.9, 28.6], [459, 196.6, 28.4], [476, 196.5, 28.3], [493, 196, 28]];   // seg-native-quicktap.md quick90c (t ms since down, w, h)
      const natAt = (t, k) => { if (t <= NAT[0][0]) return k === 1 ? 196 : 28; for (let i = 1; i < NAT.length; i++) if (t <= NAT[i][0]) { const a = NAT[i - 1], b = NAT[i], u = (t - a[0]) / (b[0] - a[0]); return a[k] + (b[k] - a[k]) * u; } return k === 1 ? 196 : 28; };
      const c0 = (() => { const r = lensQ.getBoundingClientRect(); return r.left + r.width / 2; })();
      const tDown = performance.now(); pev(sg, "pointerdown", at(selB)); await sleep(60); pev(sg, "pointerup", at(selB));
      const fr = []; let blank = 0; const tEnd = tDown + 620;
      while (performance.now() < tEnd) { await new Promise(requestAnimationFrame); const r = lensQ.getBoundingClientRect(), L = window.__segLens, p = L && typeof L.p === "number" ? L.p : 0;
        if (sg.classList.contains("lift") && !(p > 0)) blank++; fr.push({ t: performance.now() - tDown, w: r.width, h: r.height, c: r.left + r.width / 2, p }); }
      const peak = fr.reduce((m, f) => f.w > m.w ? f : m, fr[0]), first = fr.find((f) => f.w > 196.5), back = fr.find((f) => f.t > (peak ? peak.t : 0) && f.w <= 196.5);
      /* the probe stamps each lens rect at the frame's targetTimestamp = its display time, one frame after the value was computed; our rAF samples are the
         values computed for the next display → the native list is read at t + 16.7 ms (the 60 Hz frame) for the frame-wise comparison; both rms are reported */
      const mid = fr.filter((f) => f.t >= 109 && f.t <= 476), rmsAt = (k, shift) => Math.sqrt(mid.reduce((s, f) => s + Math.pow((k === 1 ? f.w : f.h) - natAt(f.t + shift, k), 2), 0) / Math.max(1, mid.length));
      const rmsW0 = rmsAt(1, 0), rmsH0 = rmsAt(2, 0), rmsW = rmsAt(1, -16.7), rmsH = rmsAt(2, -16.7);
      const drift = Math.max(...fr.map((f) => Math.abs(f.c - c0)));
      check("分段 #9① 快速点已选中段（60 ms 抬手）：平台任何一帧不空白——带 .lift 的帧 p 必 > 0（9① 前 DestOut 在 p = 0 也给 .lift），不换值、选中不变", "blank 0 · renders = · on same", `${fr.length} frames · blank ${blank} · renders+${R.n - r9} · on ${bs().findIndex((b) => b.classList.contains("on"))}`, fr.length > 20 && blank === 0 && R.n === r9 && bs().findIndex((b) => b.classList.contains("on")) === onIdx0);
      check("分段 #9② / R9②″ 快速点已选中段原地抬落（落回弹簧建于 down + 220 ms = liftTime + lensHangTime，R87 / R88 钩子 220.9…222.1；抬手先后皆同；原生峰帧 +241…+257 = 220 + 送达 + 定时器迟到 + 帧量化）：首个长大帧 +95…+145、峰时刻 +215…+265、+430…+515 回 ≤ 196.5（原生 +474…+497）、中心不动（≤ .5 pt）", "first 95–145 · peak @225–270 · back 450–515 · drift ≤ .5", `first ${first ? first.t.toFixed(0) : "-"} · peak @${peak ? peak.t.toFixed(0) : "-"} · back ${back ? back.t.toFixed(0) : "-"} · drift ${drift.toFixed(2)}`, !!first && first.t >= 95 && first.t <= 145 && !!peak && peak.t >= 215 && peak.t <= 265 && !!back && back.t >= 430 && back.t <= 515 && drift <= 0.5);
      check("分段 #9② 峰与逐帧（记录，不判）：原生 quick90c 峰 217.5×42.4 @242；页面峰 = 抬起 ζ1/.25 自 +109 到 +242 的解析值 216.3×41.5 + 落回起步的速度惯性；差 ≈ 一帧——原生表在 +109 那帧已是 198.2（抬起起点早于 109 或探针按显示时刻记帧），待读；rms 对表 不移 / 原生前移一帧", "记录", `peak ${peak ? peak.w.toFixed(1) + "×" + peak.h.toFixed(1) : "-"} · rms w ${rmsW0.toFixed(2)} h ${rmsH0.toFixed(2)} · shifted −16.7 ms: w ${rmsW.toFixed(2)} h ${rmsH.toFixed(2)}`, true);
      await segRest(500); }
    /* a page re-render (heartbeat / snapshot) while the lens rests on a segment must not move it (the carry-over reads the lens box, not the % translate) */
    { await segRest(1300); const sg = q(), ln = sg.querySelector(".lens"), lb = ln.getBoundingClientRect().left; window.render(); const ln2 = q().querySelector(".lens"); const lb2 = ln2.getBoundingClientRect().left; await sleep(120); const lb3 = q().querySelector(".lens").getBoundingClientRect().left;
      check("重画时透镜不动（心跳/快照 render 不会让它跳）", `${Math.round(lb)}`, `${Math.round(lb2)} → ${Math.round(lb3)} ${q().querySelector(".lens").classList.contains("spring") ? "spring!" : ""}`, Math.abs(lb2 - lb) < 1 && Math.abs(lb3 - lb) < 1 && !q().querySelector(".lens").classList.contains("spring")); }
    /* §1 G14: the same segment tapped three times - one event */
    const sameName = (bs().find((x) => !x.classList.contains("on")) || bs()[0]).textContent;
    const r8 = R.n; for (let k = 0; k < 3; k++) { const b = bs().find((x) => x.textContent === sameName); const sg = q(); pev(sg, "pointerdown", at(b)); pev(sg, "pointerup", at(b)); await sleep(40); }
    check("分段 G14 同段连点 3 下：只 1 次事件", 1, R.n - r8, R.n - r8 === 1);
    const back = bs().find((b) => b.textContent === start); if (back && onText() !== start) { const sg = q(); pev(sg, "pointerdown", at(back)); pev(sg, "pointerup", at(back)); }
    /* 验收 09-19 17:5x: a one-queue page (one segment, 400 wide) re-rendered twice showed a lifted capsule (the preloaded set's width, left) on the resting
       control — the package's warm-up frame put back by the next warm-up (view.js segGlRedraw). Here: one segment, two re-renders 400 ms apart, then
       the package must have drawn exactly ONE frame per re-render (its warm-up; the put-back would be a second) and the control must be at rest. */
    if (q().classList.contains("gl") && typeof snap === "object" && snap && Array.isArray(snap.queues) && snap.queues.length > 1) {
      await sleep(900); const savedQ = snap.queues, savedCur = curQueue; snap.queues = savedQ.slice(0, 1); curQueue = snap.queues[0]["名"]; window.render(); await sleep(1500);
      const s1 = q(), g1 = s1 && s1.__gl, f0 = g1 ? g1.lens.stats.frames : -1;
      window.render(); await sleep(400); const f1 = q().__gl ? q().__gl.lens.stats.frames : -1;
      window.render(); await sleep(400); const f2 = q().__gl ? q().__gl.lens.stats.frames : -1; const s2 = q();
      check("一段控件重渲染两次：包每次只画预热那一帧（frames +1/+1，不把上一帧「放回」——放回即幽灵胶囊；view.js segGlRedraw），控件静止（无 .lift，一个 canvas）", "+1 / +1 · rest", `${s2.querySelectorAll("button").length} seg · frames ${f0} → ${f1} → ${f2} · ${s2.classList.contains("lift") ? "lift!" : "rest"} · ${s2.querySelectorAll("canvas.glens").length} canvas`, s2.querySelectorAll("button").length === 1 && f1 - f0 === 1 && f2 - f1 === 1 && !s2.classList.contains("lift") && s2.querySelectorAll("canvas.glens").length === 1);
      snap.queues = savedQ; curQueue = savedCur; window.render(); await sleep(600);
    }
  }
  /* 监督局 19:3x: a segment tap must not flash — the buttons carry no tap highlight and no pointer focus ring (unchanged since 181053), and a render must not
     rebuild the tab bar's nodes (the platter's backdrop-filter layer / glide / buttons stay the same elements) */
  if (sec("render", { layer: "timing" })) { const sb = document.querySelector("#queueseg button"), nv = document.querySelector("nav.tabs"), plat0 = nv && nv.querySelector(".plat"), gl0 = nv && nv.querySelector(".glide"), b0 = nv && nv.querySelector(".seg > button");
    const th = sb ? getComputedStyle(sb).webkitTapHighlightColor : "-", fv = sb ? sb.matches(":focus-visible") : null;
    window.render(); await sleep(50); window.render(); await sleep(50);
    const same = nv && plat0 === nv.querySelector(".plat") && gl0 === nv.querySelector(".glide") && b0 === nv.querySelector(".seg > button");
    check("分段按钮无点按高亮（-webkit-tap-highlight-color transparent，index.html:82）、无指针焦点环（:focus-visible 不匹配）；重画两次后标签栏节点不重建（.plat / .glide / 按钮同一元素）", "transparent · no ring · same nodes", `${th} · focus-visible ${fv} · nodes ${same ? "same" : "REBUILT"}`, /rgba\(0, 0, 0, 0\)|transparent/.test(th) && fv === false && same === true); }
  }, { layer: "timing" });
})();
