/* accept-alert.js — acceptance of the alert panel's glass (BOARD R57 / R57′; alert-glass.js). Registered through ACCEPT.add; runs in accept.js's page,
   once per theme (the harness runs light and dark).
   Rows: the keys in the code = the 70-key truths (alert-native-formula.md §4 ⑦: uiprobe-deep-alert-glasskeys-{light2,dark}.json materials[11]/[60]) — the
   light column and the 17 dark differences; the layer exists while the dialog is open in BOTH themes and the pane's sampled substitute is off; the three
   filters carry the formulas (level σ = std ÷ .25, the dimming flood, the face matrix with the premultiplied fill, the MaxLuma LUTs, the bleed's tiled
   capture average and its weight LUT, the maps' scale, the highlight's vibrant matrix = the dump); the images and regions sit on the panel box; the
   five-grey flat check (headless Chrome, scratch alert-flat.py) against ⑦'s closed chain is recorded with its numbers; the layer is stripped on close. */
(function () {
  if (!window.ACCEPT) return;
  ACCEPT.add(async function acceptAlert(ctx) {
    const { check, num, sleep } = ctx;
    if (!window.AlertGlass) { check("弹窗玻璃：AlertGlass 未装载（alert-glass.js 未到）", "AlertGlass", "缺", false); return; }
    const A = window.AlertGlass, K = A.keys, D = A.dark, th = A.theme(), k = A.keysFor(th);
    check("弹窗玻璃 键（亮，70 键真值 §4 ⑦）：模糊 5 / .8 .4 .5 / −86 −1 0；面 1.03 / .4 / 饱和 1.2 / 填充 (1,1,1,.2) / MaxLumaSDR .94；折射 −60/20 · 43/34.4 · .6 · 距 −1/0；BlurFill 8 / 亮 .9 / 常 .5；Bleed 60.2×3 / .5 / 白 1 黑 .9 饱和 1.2 / darken 1 / 距 1/0；捕获 .25 / 60.2；调暗 .2", "见左",
      `${K.BlurRadius} · ${K.BlurOpacity0}/${K.BlurOpacity1}/${K.BlurOpacity2} · ${K.BlurDistance0}/${K.BlurDistance1}/${K.BlurDistance2} · 面 ${K.FaceColorMatrixWhite}/${K.FaceColorMatrixBlack}/${K.FaceColorMatrixSaturation} 填 ${K.FaceColorMatrixFillColor.join(",")} SDR ${K.FaceColorMatrixMaxLumaSDR} · 折 ${K.InnerRefractionAmount}/${K.InnerRefractionHeight} ${K.OuterRefractionAmount}/${K.OuterRefractionHeight} ${K.RefractionOpacity} 距 ${K.RefractionDistance0}/${K.RefractionDistance1} · BF ${K.BlurFillBlurRadius}/${K.BlurFillLightenOpacity}/${K.BlurFillNormalOpacity} · Bleed ${K.BleedAmount}/${K.BleedHeight}/${K.BleedBlurRadius} ${K.BleedOpacity} ${K.BleedColorMatrixWhite}/${K.BleedColorMatrixBlack}/${K.BleedColorMatrixSaturation} ${K.BleedDarkenBlend} ${K.BleedDistance0}/${K.BleedDistance1} · 捕 ${K.CaptureScale}/${K.CaptureMargin} · 暗 ${K.Dimming}`,
      K.BlurRadius === 5 && K.BlurOpacity0 === 0.8 && K.BlurOpacity1 === 0.4 && K.BlurOpacity2 === 0.5 && K.BlurDistance0 === -86 && K.BlurDistance1 === -1 && K.BlurDistance2 === 0 && K.FaceColorMatrixWhite === 1.03 && K.FaceColorMatrixBlack === 0.4 && K.FaceColorMatrixSaturation === 1.2 && K.FaceColorMatrixFillColor.join() === "1,1,1,0.2" && K.FaceColorMatrixMaxLumaSDR === 0.94
      && K.InnerRefractionAmount === -60 && K.InnerRefractionHeight === 20 && K.OuterRefractionAmount === 43 && K.OuterRefractionHeight === 34.4 && K.RefractionOpacity === 0.6 && K.RefractionDistance0 === -1 && K.RefractionDistance1 === 0 && K.BlurFillBlurRadius === 8 && K.BlurFillLightenOpacity === 0.9 && K.BlurFillNormalOpacity === 0.5
      && K.BleedAmount === 60.2 && K.BleedHeight === 60.2 && K.BleedBlurRadius === 60.2 && K.BleedOpacity === 0.5 && K.BleedColorMatrixWhite === 1 && K.BleedColorMatrixBlack === 0.9 && K.BleedColorMatrixSaturation === 1.2 && K.BleedDarkenBlend === 1 && K.BleedDistance0 === 1 && K.BleedDistance1 === 0 && K.CaptureScale === 0.25 && K.CaptureMargin === 60.2 && K.Dimming === 0.2);
    check("弹窗玻璃 键（暗，17 处材质不同 + 调暗，数据 R74）：面 1.125 / .125 / 1.3 / 填充 α 0 / MaxLuma .35 = SDR .35；钳 1.3083；KeyFill spread 1.309/1.309；影 .6；Bleed 白 .5 黑 .125 饱和 1 / darken 0 / .8；BlurFill 亮 0 暗 .9；调暗 .48", "18 项如左",
      `${Object.keys(D).length} 项 · 面 ${D.FaceColorMatrixWhite}/${D.FaceColorMatrixBlack}/${D.FaceColorMatrixSaturation} 填 α ${D.FaceColorMatrixFillColor[3]} ML ${D.FaceColorMatrixMaxLuma}/${D.FaceColorMatrixMaxLumaSDR} · 钳 ${D.Clamp} · KF ${D.KeyFillHighlightSpread}/${D.KeyFillHighlightSpreadSDR} · 影 ${D.ShadowOpacity} · Bleed ${D.BleedColorMatrixWhite}/${D.BleedColorMatrixBlack}/${D.BleedColorMatrixSaturation} ${D.BleedDarkenBlend} ${D.BleedOpacity} · BF ${D.BlurFillLightenOpacity}/${D.BlurFillDarkenOpacity} · 暗 ${D.Dimming}`,
      Object.keys(D).length === 18 && D.FaceColorMatrixWhite === 1.125 && D.FaceColorMatrixBlack === 0.125 && D.FaceColorMatrixSaturation === 1.3 && D.FaceColorMatrixFillColor[3] === 0 && D.FaceColorMatrixMaxLuma === 0.35 && D.FaceColorMatrixMaxLumaSDR === 0.35 && D.Clamp === 1.3083 && D.KeyFillHighlightSpread === 1.309 && D.KeyFillHighlightSpreadSDR === 1.309 && D.ShadowOpacity === 0.6
      && D.BleedColorMatrixWhite === 0.5 && D.BleedColorMatrixBlack === 0.125 && D.BleedColorMatrixSaturation === 1 && D.BleedDarkenBlend === 0 && D.BleedOpacity === 0.8 && D.BlurFillLightenOpacity === 0 && D.BlurFillDarkenOpacity === 0.9 && D.Dimming === 0.48);
    const dlg = document.getElementById("alert"); if (!dlg || typeof ask !== "function") { check("弹窗玻璃：#alert / ask() 不可用", "有", "缺", false); return; }
    /* S1 (SPEED2, 2号 13:1x): the fixed waits are waits on the layer's own flags — the copy on the full chain (the light-first open swapped, alert-glass.js), the
       stroke layer present (built on .settled), the layer gone after the close — each capped at the old sleep's length */
    const frame = () => new Promise((r) => requestAnimationFrame(r));
    const pt = (e, a) => +e.getAttribute(a) * (+(e.closest("filter") || e).dataset.gres || 1);   // f0 / f1 / f2 run at 1 / G (alert-glass.js gres): lengths back in page units
    const until = async (cond, cap) => { const t0 = performance.now(); while (!cond()) { if (performance.now() - t0 >= cap) return null; await frame(); } return performance.now() - t0; };
    const fullChain = () => !!A.layer && /alert-glass-f1/.test(A.layer.querySelector(".alert-glass-copy")?.style.filter || "") && /alert-glass-f3/.test(A.layer.querySelector(".alert-glass-w3")?.style.filter || "");
    const aend = []; let settledAt = null; const onEnd = (e) => aend.push(e.animationName + "@" + (e.target === dlg ? "dialog" : (e.target.className || e.target.tagName)));
    const mo = new MutationObserver(() => { if (settledAt === null && dlg.classList.contains("settled")) settledAt = aend.slice(); }); dlg.addEventListener("animationend", onEnd, true); mo.observe(dlg, { attributes: true, attributeFilter: ["class"] });
    const p = ask("检查", "弹窗玻璃检查", "好", false); await until(fullChain, 120);
    const layer = A.layer, pane = dlg.querySelector(".pane"), cs = pane && getComputedStyle(pane), f1 = document.getElementById("alert-glass-f1"), f2 = document.getElementById("alert-glass-f2"), f3 = document.getElementById("alert-glass-f3");
    const dark = th === "dark";
    check(`弹窗玻璃（${dark ? "暗" : "亮"}）：层在（#app 复本 → f1 接 f2，包 3 → f3）、pane 的采样替代关（backdrop-filter none、背景透明）、类 glass-read${dark ? " + glass-dark" : ""}`, "层 f1·f2·f3 · none · transparent · 类", `${layer ? "层" : "无"} ${A.layer && /f1/.test(A.layer.querySelector(".alert-glass-copy")?.style.filter || "") ? "f1" : "-"}·${/f2/.test(A.layer?.querySelector(".alert-glass-copy")?.style.filter || "") ? "f2" : "-"}·${/f3/.test(A.layer?.querySelector(".alert-glass-w3")?.style.filter || "") ? "f3" : "-"} · ${cs ? (cs.webkitBackdropFilter || cs.backdropFilter) : "-"} · ${cs ? cs.backgroundColor : "-"} · ${dlg.classList.contains("glass-read") ? "glass-read" : "-"}${dlg.classList.contains("glass-dark") ? "+glass-dark" : ""}`,
      !!layer && !!cs && /none/.test(cs.webkitBackdropFilter || cs.backdropFilter || "none") && /rgba\(0, 0, 0, 0\)|transparent/.test(cs.backgroundColor) && dlg.classList.contains("glass-read") && dlg.classList.contains("glass-dark") === dark && !!f1 && !!f2 && !!f3 && f1.dataset.theme === th
      && /alert-glass-f1/.test(layer.querySelector(".alert-glass-copy")?.style.filter || "") && /alert-glass-f2/.test(layer.querySelector(".alert-glass-copy")?.style.filter || "") && /alert-glass-f3/.test(layer.querySelector(".alert-glass-w3")?.style.filter || ""));
    const sig = f1 ? f1.dataset.sigma.split(",").map(Number) : [NaN, NaN], dim = f1 && f1.querySelector('feFlood[result="dim"]'), nimg = [f1, f2, f3].reduce((n, f) => n + (f ? f.querySelectorAll("feImage").length : 0), 0);
    check(`弹窗玻璃 f1：调暗 flood 黑 α ${k.Dimming}（UIDimmingView）在捕获之下；两级金字塔 σ = 级 std ÷ 捕获比 .25（2.147 / 4.694 → 8.588 / 18.776 pt）；三滤镜共 6 张生成图（权 / 内折射 / 外折射 / bleed / 高光 ×2）`, `${k.Dimming} · 8.588 / 18.776 · 6 图`, `${dim ? dim.getAttribute("flood-opacity") : "-"} · ${sig.map((v) => v.toFixed(3)).join(" / ")} · ${nimg} 图`, !!dim && +dim.getAttribute("flood-opacity") === k.Dimming && Math.abs(sig[0] - 2.147 / 0.25) < 0.002 && Math.abs(sig[1] - 4.694 / 0.25) < 0.002 && nimg === 6);
    const dm = f1 ? [...f1.querySelectorAll("feDisplacementMap")] : [], S = A.images(dlg.offsetWidth, dlg.offsetHeight).S;
    { const bfb = f1 && f1.querySelector('feGaussianBlur[result="bfb"]'), offs = f1 ? [...f1.querySelectorAll('feOffset[result="bfp"], feOffset[result="bfm"]')].map((e) => pt(e, "dx")) : [];
      check("弹窗玻璃 f1 BlurFill（menu-card-material §7c，R63′）：b = 未折射（压暗后）捕获在 mip 3（级 std 9.581 ÷ .25 = σ 38.32 pt）取 ±.75 纹素（±24 pt）平均，与折射无关；darken/lighten 混后 α 归 1", "σ 38.32 · ±24 · in src", `σ ${bfb ? pt(bfb, "stdDeviation") : "-"} · ${offs.join("/")} · in ${bfb ? bfb.getAttribute("in") : "-"}`, !!bfb && Math.abs(pt(bfb, "stdDeviation") - 9.581 / 0.25) < 0.02 && offs.length === 2 && offs[0] === 24 && offs[1] === -24 && bfb.getAttribute("in") === "src"); }
    check("弹窗玻璃 折射：内 −60/20、外 43/34.4 两张位移图（feDisplacementMap scale = 图的 S）、权 .6·sat((d + 1)/1)（RefractionDistance −1/0）", `2 · scale ${S}`, `${dm.length} · scale ${dm.map((e) => pt(e, "scale")).join("/")}`, dm.length === 2 && dm.every((e) => Math.abs(pt(e, "scale") - S) < 1e-6));
    /* f2: BlurFill → α reset → MaxLuma LUTs → face matrix (fill folded) → bleed */
    const a1 = (f1 && f1.querySelector('feComponentTransfer[result="cbf"] feFuncA')) || (f2 && f2.querySelector('feComponentTransfer[result="cbf"] feFuncA')), lA = f2 && f2.querySelector('feComponentTransfer[result="A"] feFuncR'), lB = f2 && f2.querySelector('feComponentTransfer[result="iB4"] feFuncR'), mlc = f2 && f2.querySelector('feComposite[result="ml"]');
    const comp = 1 - k.FaceColorMatrixMaxLumaSDR, kOf = (Y) => 1 - comp * Y, Aw = (Y) => kOf(Y) * (1.3 - 0.3 * kOf(Y)), iBw = (Y) => 1 - 4 * 0.3 * (1 - kOf(Y)) * kOf(Y) * Y;
    const tA = lA ? lA.getAttribute("tableValues").split(/\s+/).map(Number) : [], tB = lB ? lB.getAttribute("tableValues").split(/\s+/).map(Number) : [];
    check(`弹窗玻璃 f2 MaxLuma（§4 ⑦ IR %568–%584）：c′ = c·A(Y) − B(Y)，A = k(1.3 − .3k)、B = .3(1 − k)kY、k = 1 − ${comp.toFixed(2)}·Y；A / (1 − 4B) 各 33 样 LUT（A(1) = ${Aw(1).toFixed(4)}，1 − 4B(1) = ${iBw(1).toFixed(4)}），合成 k2 1 / k3 .25 / k4 −.25；BlurFill 后 α 归 1`, `${Aw(1).toFixed(4)} · ${iBw(1).toFixed(4)} · 33 · .25/−.25 · α[1]`,
      `${tA.length ? tA[tA.length - 1].toFixed(4) : "-"} · ${tB.length ? tB[tB.length - 1].toFixed(4) : "-"} · ${tA.length} · ${mlc ? `${mlc.getAttribute("k3")}/${mlc.getAttribute("k4")}` : "-"} · ${a1 ? `α[${a1.getAttribute("tableValues")}]` : "-"}`,
      tA.length === 33 && tB.length === 33 && Math.abs(tA[32] - Aw(1)) < 1e-4 && Math.abs(tB[32] - iBw(1)) < 1e-4 && Math.abs(tA[16] - Aw(0.5)) < 1e-4 && !!mlc && mlc.getAttribute("k3") === ".25" && mlc.getAttribute("k4") === "-.25" && !!a1 && a1.getAttribute("tableValues") === "1");
    const fm = f2 && f2.querySelector('feColorMatrix[result="face"]'); const want = A.faceMatrix(k).split(/\s+/).map(Number), got = fm ? fm.getAttribute("values").split(/\s+/).map(Number) : [];
    const bias = dark ? 0.125 : 0.8 * 0.4 + 0.2;   // grey path: (1 − a)·Black + a (fill white α .2 premultiplied, §4 ⑦) → .52 light; dark fill 0 → Black .125
    check(`弹窗玻璃 面矩阵 = (1 − a)·YCC⁻¹·diag(${k.FaceColorMatrixWhite} − ${k.FaceColorMatrixBlack}, ${k.FaceColorMatrixSaturation}, ${k.FaceColorMatrixSaturation} | ${k.FaceColorMatrixBlack})·YCC，bias + a·rgb（set_ycc_composite，预乘填充）：偏置 ${bias.toFixed(3)}`, `${want.slice(0, 5).map((v) => v.toFixed(4)).join(" ")} · 偏置 ${bias.toFixed(3)}`, `${got.slice(0, 5).map((v) => v.toFixed(4)).join(" ")} · 偏置 ${got.length === 20 ? (got[4] + got[9] + got[14]) / 3 : NaN}`,
      got.length === 20 && got.every((v, i) => Math.abs(v - want[i]) < 1e-5) && Math.abs((got[0] + got[1] + got[2]) - (1 - k.FaceColorMatrixFillColor[3]) * (k.FaceColorMatrixWhite - k.FaceColorMatrixBlack)) < 1e-3 && Math.abs(got[4] - bias) < 1e-3);
    const bb = f2 && f2.querySelector('feGaussianBlur[result="bb"]'), tile = f2 && f2.querySelector('feTile[result="tiled"]'), cap = f2 && f2.querySelector("[data-alert-cap]"), cbm = f2 && f2.querySelector('feColorMatrix[result="cb"]'), w4 = f2 && f2.querySelector('feComponentTransfer[result="w4"] feFuncR'), lx = f2 && f2.querySelector('feComponentTransfer[result="lx"] feFuncR');
    const bs = A.mixStd(A.level(k.BleedBlurRadius)) / k.CaptureScale, tw = w4 ? w4.getAttribute("tableValues").split(/\s+/).map(Number) : [], wantB = A.bleedMatrix(k).split(/\s+/).map(Number), gotB = cbm ? cbm.getAttribute("values").split(/\s+/).map(Number) : [];
    check(`弹窗玻璃 Bleed（§4 ⑦）：捕获框（面板 ± 60.2，钳到复本）平铺后 σ = min(级混 std(lod ${A.level(k.BleedBlurRadius).toFixed(2)}) ÷ .25 = ${bs.toFixed(1)}, 300/3) 模糊 = 框均值；外推位移图；色矩阵 YCC(白 ${k.BleedColorMatrixWhite} 黑 ${k.BleedColorMatrixBlack} 饱和 ${k.BleedColorMatrixSaturation})；权 = ${k.BleedOpacity}·(${k.BleedDarkenBlend ? "L" : "1 − L"})⁴ 一张 65 样 LUT × w(d)`, `tile · σ ${Math.min(bs, 100).toFixed(2)} · cb · 65 样 末 ${k.BleedOpacity} · slope ${k.BleedDarkenBlend ? 1 : -1}`,
      `${tile ? "tile" : "-"} · σ ${bb ? pt(bb, "stdDeviation") : "-"} · ${gotB.length === 20 && gotB.every((v, i) => Math.abs(v - wantB[i]) < 1e-5) ? "cb" : "cb≠"} · ${tw.length} 样 末 ${tw.length ? tw[tw.length - 1] : "-"} · slope ${lx ? lx.getAttribute("slope") : "-"}`,
      !!tile && !!bb && Math.abs(pt(bb, "stdDeviation") - Math.min(bs, 100)) < 0.01 && gotB.length === 20 && gotB.every((v, i) => Math.abs(v - wantB[i]) < 1e-5) && tw.length === 65 && Math.abs(tw[64] - k.BleedOpacity) < 1e-5 && Math.abs(tw[32] - k.BleedOpacity / 16) < 1e-4 && !!lx && +lx.getAttribute("slope") === (k.BleedDarkenBlend ? 1 : -1) && !!cap && +cap.getAttribute("width") > 0);
    const vb = f3 && f3.querySelector('feColorMatrix[result="vib_0"]'); const vv = vb ? vb.getAttribute("values").split(/\s+/).map(Number) : [];
    check("弹窗玻璃 f3 高光层：vibrantColorMatrix = dump 4×5（1.1202 −.1894 −.019 | .1471 …）两段带（主 1 pt + 漫 8 pt，spread 1.5344）", "1.1202 -0.1894 -0.019 0 0.1471 · hl hl2", `${vv.slice(0, 5).join(" ")} · ${f3 && f3.querySelector('feImage[data-alert-img="hl0"]') ? "hl" : "-"} ${f3 && f3.querySelector('feImage[data-alert-img="hl20"]') ? "hl2" : "-"}`, vv.length === 20 && Math.abs(vv[0] - 1.1202) < 1e-4 && Math.abs(vv[4] - 0.1471) < 1e-4 && !!f3 && !!f3.querySelector('feImage[data-alert-img="hl0"]') && !!f3.querySelector('feImage[data-alert-img="hl20"]'));
    check("弹窗玻璃 f3 只算面板框：区域 = 面板宽高、边距 0（f3 逐像素、面板外被 pane 的 clip-path 裁掉；原先 ±120 多算 4.5 倍像素，模拟器 D 开弹窗 187–189 帧 → 196–202 帧；面板像素与边距 120 相同 = 无头 Chrome 暗色逐一相同、亮色差 ≤ 8 与同链重拍同量，22:4x 区域落位修正后核）", `${dlg.offsetWidth}×${dlg.offsetHeight} · 0`,
      f3 ? `${pt(f3, "width")}×${pt(f3, "height")} · ${f3.dataset.margin}` : "无 f3", !!f3 && Math.abs(pt(f3, "width") - dlg.offsetWidth) < 0.5 && Math.abs(pt(f3, "height") - dlg.offsetHeight) < 0.5 && +f3.dataset.margin === 0);
    { const dr = dlg.getBoundingClientRect(), mr = document.getElementById("app").getBoundingClientRect(), bx = Math.round((dr.left + dr.width / 2 - dlg.offsetWidth / 2 - mr.left) * 10) / 10, by = Math.round((dr.top + dr.height / 2 - dlg.offsetHeight / 2 - mr.top) * 10) / 10;
      const ims = f3 ? [...f3.querySelectorAll("feImage")] : [], at = (e) => `${Math.round(pt(e, "x") * 10) / 10}, ${Math.round(pt(e, "y") * 10) / 10}`;   // margin 0 must not fall back to the default 120 (a 0 margin read as missing put the region 120 up-left: glass only in the panel's top-left 200 × 32 pt, 模拟器 D 22:36)
      check("弹窗玻璃 f3 区域与高光图落在面板框上（复本坐标左上 = 面板左上）", `${bx}, ${by}`, f3 ? `${at(f3)} · 图 ${ims.map(at).join(" / ")}` : "无 f3",
        !!f3 && ims.length === 2 && [f3, ...ims].every((e) => Math.abs(pt(e, "x") - bx) < 0.5 && Math.abs(pt(e, "y") - by) < 0.5)); }
    /* 界面 09-23: f3 runs only on the four rim strips (primitive subregions, merged over SourceGraphic) — the hl / hl2 maps are 0 deeper than hlInset, so the
       output there is SourceGraphic exactly; the maps are decoded here and every non-zero pixel must lie inside the strips (simulator B: the panel pixel-identical
       with the strips and with one full-panel strip, 0 of 3.8 M px; f3 was the costly filter at open) */
    { const W = dlg.offsetWidth, H = dlg.offsetHeight, im = A.images(W, H), sw = f3 ? +f3.dataset.stripWidth : NaN, ns = f3 ? +f3.dataset.strips : 0;
      const outside = async (href) => { const img = new Image(); img.src = href; await img.decode(); const c = document.createElement("canvas"); c.width = im.w; c.height = im.h; const x = c.getContext("2d"); x.drawImage(img, 0, 0); const d = x.getImageData(0, 0, im.w, im.h).data; let n = 0;
        for (let j = 0; j < im.h; j++) for (let i = 0; i < im.w; i++) { const px = (i + 0.5) * W / im.w, py = (j + 0.5) * H / im.h; if (d[(j * im.w + i) * 4] > 0 && Math.min(px, W - px, py, H - py) > sw - 1) n++; } return n; };
      const nOut = f3 ? (await outside(im.hl)) + (await outside(im.hl2)) : -1, merge = f3 && f3.querySelector("feMerge");
      check("弹窗玻璃 f3 只算四条边带：高光两图非零像素全在边带内（带宽 = 最深非零 + 1 pt）、四带各一条链、feMerge 叠回 SourceGraphic（带外输出 = 输入；模拟器 B 带 / 整面逐像素相同）", `4 带 · 带宽 ${Math.ceil(im.hlInset + 1)} · 带外 0`,
        `${ns} 带 · 带宽 ${sw} · 带外 ${nOut} · 合并 ${merge ? merge.children.length : 0}`, ns === 4 && sw === Math.ceil(im.hlInset + 1) && nOut === 0 && !!merge && merge.children.length === 5 && merge.children[0].getAttribute("in") === "SourceGraphic"); }
    const sh = getComputedStyle(dlg).filter, shA = dark ? 0.18 : 0.12;
    check(`弹窗玻璃 软影：drop-shadow 0 8 σ 16.9706 α ${shA}（.3 × ShadowOpacity ${k.ShadowOpacity}；σ = R 24/√2，着色器剖面 .5·erfc(d/R)，§7.3b，直边精确、角部表达差异）在 dialog 上、dialog overflow visible（R57″：pane 的 clip-path 曾把自己的影裁掉）`, `0px 8px 16.9706px rgba(0, 0, 0, ${shA}) · visible`, `${sh} · ${getComputedStyle(dlg).overflow}`, !!sh && new RegExp(`drop-shadow\\(rgba\\(0, 0, 0, ${shA}\\) 0px 8px 16.9706px\\)`).test(sh) && getComputedStyle(dlg).overflow === "visible");
    /* 19:5x (2号): the clones of #app are stills — no entrance animation replays inside them (alert-glass.css), so the only animationend reaching the dialog
       before .settled is its own alert-in (view.js:50 takes the first one; a replayed seg-in in the clone had set .settled at 124 ms of 423) */
    { await until(() => dlg.classList.contains("settled"), 800); const live = document.getAnimations().filter((x) => { const t = x.effect && x.effect.target; return t && t.closest && t.closest(".alert-glass-page, .alert-stroke-copy"); }).length;
      check("弹窗玻璃 页面副本是静帧：副本里没有重放的入场动画、.settled 由弹窗自己的 alert-in 结束触发（副本 seg-in 曾在 124 ms 冒泡把 .settled 提前、描边建在缩放中的弹窗里）", "副本动画 0 · settled 前只有 alert-in@dialog",
        `副本动画 ${live} · settled 前 ${settledAt ? settledAt.join("、") || "无" : "未 settled"}`, live === 0 && !!settledAt && settledAt.length >= 1 && settledAt.every((x) => x === "alert-in@dialog")); mo.disconnect(); dlg.removeEventListener("animationend", onEnd, true); }
    /* 21:0x (2号): nothing inside the clones may be composited — a composited descendant composites the whole filtered chain and WebKit then skips the url()
       filters for it (RenderLayerCompositor.cpp:4214, RenderLayerBacking.cpp:884; alert-glass.css). will-change is the only compositing trigger the page puts
       in #app (index.html:465 on the switch knob's ::after); the pseudo-elements are read on their own */
    { const wc = []; for (const e of document.querySelectorAll(".alert-glass-page, .alert-glass-page *, .alert-stroke-copy, .alert-stroke-copy *")) for (const ps of [null, "::before", "::after"]) { const v = getComputedStyle(e, ps).willChange; if (v !== "auto") wc.push((e.className && e.className.baseVal === undefined ? e.className : e.tagName) + (ps || "") + " " + v); }
      check("弹窗玻璃 副本里不合成：两份页面副本及其 ::before / ::after 的 will-change 全为 auto（开关圆钮 ::after 的 will-change 曾让整条玻璃链合成、三道 url 滤镜在 iOS 上被跳过，面板与不加滤镜逐像素相同）", "0 处", `${wc.length} 处${wc.length ? " · " + wc.slice(0, 3).join("、") : ""}`, wc.length === 0); }
    /* 界面 09-23: the stroke's k map is cached per size / theme / scale and pre-warmed at idle (alert-glass.js strokeCache): built inside the .settled handler
       it held the main thread 61–97 ms at the end of the appear animation (simulator B, rAF gap 79–114 ms there; cached: 1–5 ms, gap 42–44) */
    { await until(() => !!dlg.querySelector(".alert-stroke"), 600); const ms = A.strokeMs, hit = A.warmStroke(dlg.offsetWidth, dlg.offsetHeight, th);
      check("弹窗描边 k 图按尺寸缓存、闲时预热：弹窗出现动画结束时（.settled）描边构建不再逐像素算图——同尺寸再取 ≤ 2 ms（未缓存时在结束那一帧占主线程 61–97 ms，模拟器 B 帧隔 79–114 ms）", "≤ 2 ms",
        `再取 ${hit.toFixed(1)} ms · 本次 .settled 构建 ${ms == null ? "无" : ms.toFixed(1) + " ms"}`, hit <= 2); }
    /* R57″: the KeyFill stroke outside the panel (keyfill §2c, the menu's construction) once .settled, and the ring shadow band inside (keyfill §4: offset 8 / stroke 4 / σ 5 / .06, mask 1 = the pane's clip) */
    { await until(() => !!dlg.querySelector(".alert-stroke") && !!document.getElementById("alert-stroke-f"), 600); const sk = dlg.querySelector(".alert-stroke"), sf = document.getElementById("alert-stroke-f"), wantTop = dark ? 0 : 2 * (0.216 / (1 + 0.5 * (1 - 0.216))), Sw = Math.cos(k.KeyFillHighlightSpreadSDR), ring = dlg.querySelector(".alert-glass-ring path");
      check(`弹窗玻璃 着色器内 KeyFill 描边（R57″ §2c）：.settled 后描边层在 dialog 里（pane 之前）、k 图 dpr 级：左右外 1 px k 1、上下 ${wantTop.toFixed(2)}（S = cos ${k.KeyFillHighlightSpreadSDR} = ${Sw.toFixed(3)}）、底先压暗 ${k.Dimming}、链 darken + LUT + k4`, `层 · side 1 · top ${wantTop.toFixed(2)} · dim ${k.Dimming}`, sk && sf ? `${sk.nextElementSibling && sk.nextElementSibling.classList.contains("pane") ? "层" : "层(位置?)"} · side ${sf.dataset.kside} · top ${sf.dataset.ktop} · dim ${sf.dataset.dimming} · ${sf.querySelector('feBlend[result^="bmin"]')?.getAttribute("mode")}` : `无描边层（settled ${dlg.classList.contains("settled")}）`,
        !!sk && !!sf && Math.abs(+sf.dataset.kside - 1) <= 0.02 && Math.abs(+sf.dataset.ktop - wantTop) <= 0.03 && Math.abs(+sf.dataset.s - Sw) < 1e-3 && +sf.dataset.dimming === k.Dimming && sf.querySelector('feBlend[result^="bmin"]')?.getAttribute("mode") === "darken" && /evenodd/.test(sk.style.clipPath));
      check("弹窗玻璃 环影带（R57″ keyfill §4）：形下移 8、带宽 4、σ 5、黑 .06、multiply、裁在 pane 形内（mask 1）", "8/4/5/0.06 · multiply · 在 .alert-glass 内", ring ? `${ring.dataset.ring} · ${getComputedStyle(ring.closest("svg")).mixBlendMode} · ${ring.closest(".alert-glass") ? "在 .alert-glass 内" : "在外"}` : "无环影", !!ring && ring.dataset.ring === "8/4/5/0.06" && getComputedStyle(ring.closest("svg")).mixBlendMode === "multiply" && !!ring.closest(".alert-glass")); }
    /* the ring's bitmap (alert-glass.js ringBitmap, 界面 09-24): made from the same SVG at idle; an open with it in the cache shows the image, the SVG hidden */
    { const W = dlg.offsetWidth, H = dlg.offsetHeight; await AlertGlass.ringBitmap(W, H, AlertGlass.theme()); AlertGlass.rebuild(); const im = dlg.querySelector(".alert-glass-ring-img"), sv = dlg.querySelector(".alert-glass-ring"), p = sv && sv.querySelector("path");
      check("弹窗玻璃 环影位图：空闲时由同一 SVG 画成、开窗贴图（multiply、在 .alert-glass 内），原 SVG 隐藏", `img ${p ? p.dataset.ring : "-"} · multiply · 隐藏`, im ? `img ${im.dataset.ring} · ${getComputedStyle(im).mixBlendMode} · ${sv && getComputedStyle(sv).display === "none" ? "隐藏" : "SVG 还在画"}` : "无位图",
        !!im && !!p && im.dataset.ring === p.dataset.ring && getComputedStyle(im).mixBlendMode === "multiply" && !!im.closest(".alert-glass") && getComputedStyle(sv).display === "none" && im.naturalWidth > 0); }
    const im = f1 && f1.querySelector('feImage[data-alert-img="wimg0"]'); const fr = f1 && { x: pt(f1, "x"), y: pt(f1, "y") }; const dr = dlg.getBoundingClientRect(), mr = document.getElementById("app").getBoundingClientRect();
    const px = dr.left + dr.width / 2 - dlg.offsetWidth / 2 - mr.left, py = dr.top + dr.height / 2 - dlg.offsetHeight / 2 - mr.top;
    check("弹窗玻璃 对位：图落在面板框（复本坐标 = 弹窗框 − #app 框）、f1 区外扩 220、f2 区 300、捕获框 = 面板 ± 60.2 钳到复本", `img (${px.toFixed(1)}, ${py.toFixed(1)}) · f1 −220 · f2 −300 · cap ≤ 60.2`, `img (${im ? pt(im, "x") : "-"}, ${im ? pt(im, "y") : "-"}) · f1 ${fr ? (fr.x - px).toFixed(1) : "-"} · f2 ${f2 ? (pt(f2, "x") - px).toFixed(1) : "-"} · cap ${cap ? (px - pt(cap, "x")).toFixed(1) : "-"}`,
      !!im && Math.abs(pt(im, "x") - px) < 0.6 && Math.abs(pt(im, "y") - py) < 0.6 && !!fr && Math.abs(fr.x - px + 220) < 0.6 && !!f2 && Math.abs(pt(f2, "x") - px + 300) < 0.6 && !!cap && px - pt(cap, "x") <= 60.2 + 0.01 && px - pt(cap, "x") >= 0);
    /* the five-grey flat check (scratch alert-flat.py: the page a flat grey, the alert open, the pane's centre sampled in headless Chrome at dpr 3) against ⑦'s
       closed chain from the keys: the numbers below are the harness's own run of this build (2026-09-20), re-run when the chain changes */
    const chain = (Dv) => { const Dd = Dv * (1 - k.Dimming), a = k.FaceColorMatrixFillColor[3]; const c1 = Dd * (1 - comp * Dd), c2 = (1 - a) * ((k.FaceColorMatrixWhite - k.FaceColorMatrixBlack) * c1 + k.FaceColorMatrixBlack) + a;   // grey: dimming → MaxLuma → face + premultiplied fill → bleed mix (⑦'s table)
      const w = (dark ? ((1 - c2) ** 2) ** 2 : c2 ** 4) * k.BleedOpacity, cb = (k.BleedColorMatrixWhite - k.BleedColorMatrixBlack) * Dd + k.BleedColorMatrixBlack; return (c2 + w * (cb - c2)) * 255; };
    const measured = dark ? [116, 102, 82, 57, 32] : [236, 216, 190, 164, 136], greys = [255, 192, 128, 64, 0], pred = greys.map((g) => chain(g / 255)), dmax = Math.max(...measured.map((m, i) => Math.abs(m - pred[i])));
    check(`弹窗玻璃 五灰阶平底核（${dark ? "暗" : "亮"}，⑦ 闭链：${pred.map((v) => v.toFixed(1)).join(" / ")}；无头 Chrome 实测记录）`, "|Δ| ≤ 1.25/255", `${measured.join(" / ")} · |Δ|max ${dmax.toFixed(2)}`, dmax <= 1.25 && Math.abs(pred[0] - (dark ? 117.2 : 237.0)) < 0.15);
    /* R57⁗ (§4 ⑨ R83, R85: materials[62].gradientOvalization .5): g = normalize(mix(shape normal, normalize((x, hw/hh·y)), .5)) turns the map directions towards the centre along the long
       edges — on the 320-wide panel the top edge at x = ±120 gives (.316, −.949) (18° off the vertical), x = ±150 (.368, −.930); read back from the inner refraction map (R/G = 128 + D·255/S) */
    { const im = A.images(dlg.offsetWidth, dlg.offsetHeight), W = dlg.offsetWidth, H = dlg.offsetHeight, xq = 120.25, yq = -H / 2 + 2.25; const gs = A.sdf(xq, yq, W / 2, H / 2, k.CornerRadius), gA = A.gOval(xq, yq, W / 2, H / 2, gs[1], gs[2], k.GradientOvalization), ang = Math.atan2(gA[0], -gA[1]) * 180 / Math.PI, angS = Math.atan2(gs[1], -gs[2]) * 180 / Math.PI;   // the shape normal there is already tilted: x = 120 lies in the supercircle's corner zone (R = 1.5287 × 34 = 52 from the corner)
      const dec = await new Promise((res) => { const img = new Image(); img.onload = () => { const c = document.createElement("canvas"); c.width = im.w; c.height = im.h; const x = c.getContext("2d"); x.drawImage(img, 0, 0); const px = Math.round((W / 2 + 120) * 2), py = Math.round(2 * 2); const d = x.getImageData(px, py, 1, 1).data; res([(d[0] - 128) / 255 * im.S, (d[1] - 128) / 255 * im.S]); }; img.onerror = () => res(null); img.src = im.inner; });
      const sgn = Math.sign(k.InnerRefractionAmount) || 1, angMap = dec ? Math.atan2(sgn * dec[0], -sgn * dec[1]) * 180 / Math.PI : NaN;   // the inner map's D = amount·Dc·g with amount −60: the vector points against g
      const want = Math.atan2(0.316, 0.949) * 180 / Math.PI;   // §4 ⑨'s worked point (a box normal (0, −1) at x = 120 → (.316, −.949) = 18.4°); the supercircle's own normal is already tilted there, so the built value is mix(shape, oval)
      check(`弹窗玻璃 梯度椭圆化 .5（R85 键；§4 ⑨ 只改梯度）：键 .5；顶边 x = +120（内 2 pt）：形法线 ${angS.toFixed(1)}° → 椭圆化后 ${ang.toFixed(1)}°（⑨ 以盒法线算 ${want.toFixed(1)}°），内折射图同点 ${isNaN(angMap) ? "-" : angMap.toFixed(1)}°（±3°）`, `.5 · 椭圆化后 > 形法线 · 图 = 式 ± 3°`, `${k.GradientOvalization} · ${angS.toFixed(1)}° → ${ang.toFixed(1)}° · 图 ${isNaN(angMap) ? "-" : angMap.toFixed(1)}°`, k.GradientOvalization === 0.5 && ang > angS + 5 && !isNaN(angMap) && Math.abs(angMap - ang) < 3); }
    check("弹窗玻璃 不可表达 / 未读记录（AlertGlass.unbuilt）：钳 no-op、描边只在落定后（形变期无）、d′、bleed 捕获边（平铺 vs clamp_to_edge）、BlurFill 纹素对读法", "5 项", `${Object.keys(A.unbuilt).length} 项`, Object.keys(A.unbuilt).length === 5 && !A.unbuilt.Dark && !A.unbuilt.GradientOvalization);
    document.getElementById("alert-cancel").click(); await p; await until(() => !A.layer && !dlg.open, 500);
    /* R57‴: an open whose maps are not cached (a new height: a three-line message) paints its first frame on the light chain (#alert-glass-f0, no generated images) and switches
       to f1 / f2 / f3 after that frame; the size is remembered for the idle pre-warm of the next load */
    { const msg3 = "第一行说明\n第二行说明\n第三行说明——换个高度让贴图缓存未命中";
      /* 0fe960c simulator A: a real browser keeps localStorage between runs, so this size was the last one opened and the idle pre-warm had already generated its maps —
         the open went straight to f1 (by design) and warmedAt was a minute old (−59028 ms). Open it once, then drop that size's maps so the timed open is a real miss */
      { const q = ask("检查", msg3, "好", false); await until(() => !!A.layer, 200); const W3 = dlg.offsetWidth, H3 = dlg.offsetHeight; document.getElementById("alert-cancel").click(); await q; await until(() => !A.layer && !dlg.open, 500); await A.imagesAsync(W3, H3); A.forget(W3, H3); }   // the priming open's maps finished first (界面 09-23: a worker still busy with them delayed the timed miss past 200 ms in the full run)
      /* 界面 09-23: the maps now come from the map worker, which in Chrome can answer before the first rAF (10 ms) — so the light chain is read where build()
         leaves it (the open's MutationObserver, one microtask after ask()), not at the first frame; the open's main thread never builds the maps either way */
      const tAsk = performance.now(), p3 = ask("检查", msg3, "好", false); await Promise.resolve();
      const c3 = dlg.querySelector(".alert-glass-copy"), f0 = c3 && /alert-glass-f0/.test(c3.style.filter), light1 = A.light, viaWorker = /^worker/.test(A.mapWorker);
      /* the maps arrive from a real-time thread while the page runs on CDP virtual time (accept-run.py S3), which runs ahead while the page idles: a page-time cap
         on the worker measured 1.4 s here for 83 ms on simulator B (43–46 ms maps + 29–35 ms PNG, 09-23 23:03) — so the wait is on the maps themselves, then the
         switch must follow within 2 frames */
      await A.imagesAsync(dlg.offsetWidth, dlg.offsetHeight); const tMaps = performance.now(); const sw = await until(fullChain, 200); const swFrames = sw == null ? null : Math.round((performance.now() - tMaps) / 16.7);
      const full = c3 && /alert-glass-f1/.test(c3.style.filter) && /alert-glass-f2/.test(c3.style.filter) && /alert-glass-f3/.test(dlg.querySelector(".alert-glass-w3")?.style.filter || "");
      check(`弹窗玻璃 首开（贴图未缓存）：开窗时走轻链 f0（无生成图，图交后台线程）、图到即换 f1/f2/f3（图到后 ${swFrames == null ? "未换" : swFrames + " 帧"}；模拟器 B 开窗后 +83 ms）、尺寸记入 ark-alert-size（下次载入空闲预热）`, "f0 开窗 · 后台 · 图到 ≤ 2 帧满链 · 记尺寸", `${f0 && light1 ? "f0 开窗" : `开窗 ${c3 ? c3.style.filter : "-"} light ${light1}`} · ${viaWorker ? "后台" : A.mapWorker} · ${full ? "满链" : "未换"} · ${localStorage.getItem("ark-alert-size") === dlg.offsetWidth + "x" + dlg.offsetHeight ? "记尺寸" : "尺寸未记"}`, f0 && light1 && viaWorker && full && swFrames != null && swFrames <= 2 && !A.light && localStorage.getItem("ark-alert-size") === dlg.offsetWidth + "x" + dlg.offsetHeight && A.cached(dlg.offsetWidth, dlg.offsetHeight));
      document.getElementById("alert-cancel").click(); await p3; await until(() => !A.layer && !dlg.open, 500); }
    /* 界面 09-23: an uncached size's maps come from the map worker (alert-glass.js imagesAsync) — the open's main thread no longer builds them (simulator B: 86–97 ms
       there, the cold open's rAF gap 71–96 ms) — and they are the main-thread build's pixels */
    { const W = 320, H = 401; A.forget(W, H); const wk = await A.imagesAsync(W, H), state = A.mapWorker; A.forget(W, H); const mn = A.images(W, H); A.forget(W, H);
      const px = async (u) => { const img = new Image(); img.src = u; await img.decode(); const c = document.createElement("canvas"); c.width = img.naturalWidth; c.height = img.naturalHeight; const x = c.getContext("2d"); x.drawImage(img, 0, 0); return x.getImageData(0, 0, c.width, c.height).data; };
      let diff = 0; for (const n of ["weights", "inner", "outer", "hl", "hl2", "bleed"]) { const a = await px(wk[n]), b = await px(mn[n]); if (a.length !== b.length) diff += Math.max(a.length, b.length); else for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) diff++; }
      check("弹窗玻璃 贴图在后台线程生成：未缓存尺寸的六张图由后台线程出（开窗主线程不再逐像素算图；模拟器 B 曾占 86–97 ms、开窗帧隔 71–96 ms），与主线程生成逐像素相同、带宽参数相同", "后台 · 0 处不同",
        `${state} · ${diff} 处不同 · 带宽 ${wk.hlInset}/${mn.hlInset}`, /^worker/.test(state) && diff === 0 && wk.hlInset === mn.hlInset); }
    check("弹窗玻璃：关掉后层撤（含描边层）", "无", A.layer || dlg.querySelector(".alert-stroke") ? "层" : "无", !A.layer && !dlg.querySelector(".alert-stroke"));
  }, { layer: "timing", dark: true });   // S4 file-level tags (数据 S4-tags.md (e), 2号 13:5x): timing = waits on the drivers, so ?layer=daily and release both run it; dark true = the 70 light / 18 dark keys (R74)
})();
